/**
 * RevealsMap.ts — Reveals the entire map shroud/fog for qualifying owner relationships
 * OpenRA 对照: OpenRA.Mods.Common/Traits/RevealsMap.cs
 *
 * 核心范式转换:
 * - C# ConditionalTrait<RevealsMapInfo> → TS ConditionalTrait<RevealsMapInfo>
 * - C# explicit interface implementations (INotifyKilled, INotifyActorDisposing,
 *   INotifyOwnerChanged) → TS implements clause
 * - C# self.World.Map.ProjectedCells → TS (self.world as any).map.projectedCells
 * - C# player.Shroud.AddSource/RemoveSource → TS player.shroud.addSource/removeSource
 * - C# Shroud.SourceType enum → TS SourceType const object
 * - C# ValidRelationships.HasRelationship() → TS PlayerRelationshipExts.hasRelationship()
 *
 * NOTE: RevealsMap does not inherit AffectsShroud. It is a standalone trait that
 * toggles full-map visibility purely through the condition system.
 */

import {
  ConditionalTrait,
  type ConditionalTraitInfo,
  type IGameActor,
  type INotifyKilled,
  type INotifyActorDisposing,
  type INotifyOwnerChanged,
  type AttackInfo,
  type PlayerStub,
  PlayerRelationship,
  PlayerRelationshipExts,
} from '../../OpenRA.Game/Traits/TraitsInterfaces.js'
import type { PPos } from '../../OpenRA.Game/MPos.js'
import { SourceType } from '../../OpenRA.Game/Traits/Player/Shroud.js'
import type { Player } from '../../OpenRA.Game/Player.js'
import type { Map as GameMap } from '../../OpenRA.Game/Map/Map.js'

// ---------------------------------------------------------------------------
// RevealsMapInfo (OpenRA 对照: RevealsMapInfo)
// ---------------------------------------------------------------------------

/**
 * Configuration for the map-reveal trait.
 *
 * OpenRA 对照: RevealsMapInfo : ConditionalTraitInfo
 *
 * When the condition expression is satisfied, reveals the entire map to all
 * players whose relationship matches validRelationships.
 */
export class RevealsMapInfo implements ConditionalTraitInfo {
  /** Optional instance name for trait disambiguation. */
  readonly instanceName?: string

  /** Optional condition expression that must be satisfied for the trait to be active. */
  readonly requiresCondition?: string

  /**
   * Relationship mask determining which players receive the map reveal.
   *
   * OpenRA 对照: ValidRelationships (default PlayerRelationship.Ally)
   */
  readonly validRelationships: PlayerRelationship = PlayerRelationship.Ally

  /**
   * Whether to reveal fog generated by the CreatesShroud trait.
   *
   * OpenRA 对照: RevealGeneratedShroud (default true)
   */
  readonly revealGeneratedShroud: boolean = true

  constructor(params: {
    instanceName?: string
    requiresCondition?: string
    validRelationships?: PlayerRelationship
    revealGeneratedShroud?: boolean
  } = {}) {
    this.instanceName = params.instanceName
    this.requiresCondition = params.requiresCondition
    if (params.validRelationships !== undefined) this.validRelationships = params.validRelationships
    if (params.revealGeneratedShroud !== undefined) this.revealGeneratedShroud = params.revealGeneratedShroud
  }
}

// ---------------------------------------------------------------------------
// RevealsMap (OpenRA 对照: RevealsMap)
// ---------------------------------------------------------------------------

/**
 * Reveals the entire map when the condition is satisfied.
 *
 * OpenRA 对照: RevealsMap : ConditionalTrait<RevealsMapInfo>
 *
 * When the condition expression is satisfied (trait enabled), adds all projected
 * cells on the map as visibility sources to each player whose relationship matches
 * validRelationships. When the condition is no longer satisfied, or the actor dies
 * or changes owner, the visibility sources are removed.
 *
 * SourceType is determined by revealGeneratedShroud:
 * - true → SourceType.Visibility (visibility + fog generated by CreatesShroud)
 * - false → SourceType.PassiveVisibility (normal visible area only)
 */
export class RevealsMap
  extends ConditionalTrait<RevealsMapInfo>
  implements INotifyKilled, INotifyActorDisposing, INotifyOwnerChanged
{
  /** Pre-set visibility source type based on revealGeneratedShroud config. */
  private readonly _sourceType: SourceType

  constructor(info: RevealsMapInfo) {
    super(info)
    this._sourceType = info.revealGeneratedShroud
      ? SourceType.Visibility
      : SourceType.PassiveVisibility
  }

  // -------------------------------------------------------------------------
  // Protected helpers (OpenRA 对照: protected methods)
  // -------------------------------------------------------------------------

  /**
   * Returns the projected cells array for the entire map.
   *
   * OpenRA 对照: RevealsMap.ProjectedCells(Actor)
   *
   * @param self — the actor this trait is attached to
   * @returns read-only array of all projected cells, or empty if the map is unavailable
   */
  protected _projectedCells(self: IGameActor): readonly PPos[] {
    const map = this._getMap(self)
    if (!map) return RevealsMap._EMPTY_CELLS
    return map.projectedCells
  }

  /**
   * Adds visibility sources to a specific player's shroud.
   *
   * OpenRA 对照: RevealsMap.AddCellsToPlayerShroud(Actor, Player, PPos[])
   *
   * Sources are only added if the actor's owner has a valid relationship
   * with the target player.
   *
   * @param self — the actor this trait is attached to
   * @param player — the player whose shroud to modify
   * @param cells — projected cells to add as visibility sources
   */
  protected _addCellsToPlayerShroud(
    self: IGameActor,
    player: Player,
    cells: readonly PPos[],
  ): void {
    const owner = self.owner as Player | null | undefined
    if (!owner) return

    const relationship = owner.relationshipWith(player)
    if (!PlayerRelationshipExts.hasRelationship(this.info.validRelationships, relationship)) {
      return
    }

    player.shroud.addSource(this, this._sourceType, cells)
  }

  /**
   * Removes this actor's visibility contribution from a specific player.
   *
   * OpenRA 对照: RevealsMap.RemoveCellsFromPlayerShroud(Player)
   *
   * @param player — the player whose shroud to modify
   */
  protected _removeCellsFromPlayerShroud(player: Player): void {
    player.shroud.removeSource(this)
  }

  // -------------------------------------------------------------------------
  // Source management (OpenRA 对照: source batch management)
  // -------------------------------------------------------------------------

  /**
   * Adds visibility sources to all players.
   *
   * OpenRA 对照: logic in TraitEnabled(Actor)
   *
   * @param self — the actor this trait is attached to
   */
  private _addSourceToAllPlayers(self: IGameActor): void {
    const cells = this._projectedCells(self)
    const players = this._getPlayers(self)
    if (!players) return

    for (const p of players) {
      this._addCellsToPlayerShroud(self, p, cells)
    }
  }

  /**
   * Removes visibility sources from all players.
   *
   * OpenRA 对照: logic in TraitDisabled(Actor)
   */
  private _removeSourceFromAllPlayers(self: IGameActor): void {
    const players = this._getPlayers(self)
    if (!players) return

    for (const p of players) {
      this._removeCellsFromPlayerShroud(p)
    }
  }

  // -------------------------------------------------------------------------
  // ConditionalTrait overrides (OpenRA 对照: TraitEnabled / TraitDisabled)
  // -------------------------------------------------------------------------

  /**
   * Called when the trait is enabled — reveals the entire map.
   *
   * OpenRA 对照: TraitEnabled(Actor)
   *
   * NOTE: super.traitEnabled() sets _enabled = true before addSourceToAllPlayers
   * is called. The framework guarantees that world / players / map are available
   * by the time lifecycle methods fire, so the _projectedCells and _getPlayers
   * helpers will return valid data here.
   */
  protected override traitEnabled(self: IGameActor): void {
    super.traitEnabled(self)
    this._addSourceToAllPlayers(self)
  }

  /**
   * Called when the trait is disabled — removes the map reveal.
   *
   * OpenRA 对照: TraitDisabled(Actor)
   */
  protected override traitDisabled(self: IGameActor): void {
    this._removeSourceFromAllPlayers(self)
    super.traitDisabled(self)
  }

  // -------------------------------------------------------------------------
  // INotifyOwnerChanged (OpenRA 对照: OnOwnerChanged)
  // -------------------------------------------------------------------------

  /**
   * Called when the actor's owner changes.
   *
   * OpenRA 对照: INotifyOwnerChanged.OnOwnerChanged(Actor, Player, Player)
   *
   * If the trait is not disabled, removes and re-adds sources for all players,
   * since the new owner may affect the relationship check.
   */
  onOwnerChanged(self: IGameActor, _oldOwner: PlayerStub, _newOwner: PlayerStub): void {
    if (this.isTraitDisabled) return

    const cells = this._projectedCells(self)
    const players = this._getPlayers(self)
    if (!players) return

    for (const p of players) {
      this._removeCellsFromPlayerShroud(p)
      this._addCellsToPlayerShroud(self, p, cells)
    }
  }

  // -------------------------------------------------------------------------
  // INotifyActorDisposing (OpenRA 对照: Disposing)
  // -------------------------------------------------------------------------

  /**
   * Called when the actor is being destroyed.
   *
   * OpenRA 对照: INotifyActorDisposing.Disposing(Actor)
   */
  disposing(self: IGameActor): void {
    this._removeSourceFromAllPlayers(self)
  }

  // -------------------------------------------------------------------------
  // INotifyKilled (OpenRA 对照: Killed)
  // -------------------------------------------------------------------------

  /**
   * Called when the actor is killed.
   *
   * OpenRA 对照: INotifyKilled.Killed(Actor, AttackInfo)
   */
  killed(self: IGameActor, _attackInfo: AttackInfo): void {
    this._removeSourceFromAllPlayers(self)
  }

  // -------------------------------------------------------------------------
  // Dispose
  // -------------------------------------------------------------------------

  /** Release resources. */
  override dispose(): void {
    super.dispose()
  }

  // -------------------------------------------------------------------------
  // Internal helpers (OpenRA 对照: world/player access)
  // -------------------------------------------------------------------------

  /** Retrieves the game map from the actor's world.
   *
   * Returns null if the world or map is not yet available (e.g. in unit tests).
   *
   * SAFETY: Casts self.world via `as any` because the IGameActor interface uses
   * WorldStub which does not declare `map`. At runtime, the world is a full
   * World instance and `world.map` is always present when the game is running.
   */
  private _getMap(self: IGameActor): GameMap | null {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const world = self.world as any
    if (!world || !world.map) return null
    return world.map as GameMap
  }

  /** Retrieves all players in the world.
   *
   * Returns null if the world is not yet available.
   *
   * SAFETY: Casts self.world via `as any` because the IGameActor interface uses
   * WorldStub which does not declare `players`. At runtime, the world is a full
   * World instance and `world.players` is always present when the game is running.
   */
  private _getPlayers(self: IGameActor): readonly Player[] | null {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const world = self.world as any
    if (!world || !world.players) return null
    return world.players as readonly Player[]
  }

  /** Pre-allocated empty array for when the map is unavailable. */
  private static readonly _EMPTY_CELLS: readonly PPos[] = Object.freeze([])
}
