/**
 * RevealsShroud.ts — Reveal fog-of-war for allied players (primary vision)
 * OpenRA 对照: OpenRA.Mods.Common/Traits/RevealsShroud.cs
 *
 * 核心范式转换:
 * - C# self.Owner.RelationshipWith(p) → TS self.owner.relationshipWith(p) with PlayerStub→Player cast
 * - C# Shroud.SourceType.Visibility / PassiveVisibility → TS SourceType.Visibility / PassiveVisibility
 * - C# revealGeneratedShroud → _sourceType selected in constructor (checked once)
 * - C# IRevealsShroudModifier range modifiers → TS traitsImplementing('IRevealsShroudModifier')
 * - C# HasRelationship extension method → TS PlayerRelationshipExts.hasRelationship
 * - C# IEnumerable<int> rangeModifiers (lazy) → TS number[] (collected once in created())
 */

import { WDist } from '../../OpenRA.Game/WDist.js'
import { PPos } from '../../OpenRA.Game/MPos.js'
import {
  AffectsShroud,
  AffectsShroudInfo,
  VisibilityType,
} from './AffectsShroud.js'
import {
  PlayerRelationship,
  PlayerRelationshipExts,
  type INotifyCreated,
  type IGameActor,
  type IRevealsShroudModifier,
} from '../../OpenRA.Game/Traits/TraitsInterfaces.js'
import { SourceType } from '../../OpenRA.Game/Traits/Player/Shroud.js'
import { applyPercentageModifiers } from '../Projectiles/MissileMath.js'
import type { Player } from '../../OpenRA.Game/Player.js'

// ---------------------------------------------------------------------------
// RevealsShroudInfo (对应 OpenRA RevealsShroudInfo)
// ---------------------------------------------------------------------------

/** Configuration for RevealsShroud trait.
 *
 * OpenRA 对照: RevealsShroudInfo : AffectsShroudInfo
 *
 * RevealsShroud clears fog of war for players whose relationship matches
 * the validRelationships mask. It is the primary vision mechanism for
 * units in the game.
 */
export class RevealsShroudInfo extends AffectsShroudInfo {
  /** Relationships the watching player needs to see the shroud removed.
   *
   * OpenRA 对照: RevealsShroudInfo.ValidRelationships (default Ally)
   */
  readonly validRelationships: PlayerRelationship

  /** Can this actor reveal shroud generated by the CreatesShroud trait?
   *
   * OpenRA 对照: RevealsShroudInfo.RevealGeneratedShroud (default true)
   *
   * When true, uses {@link SourceType.Visibility} (removes shroud / reveals
   * generated darkness). When false, uses {@link SourceType.PassiveVisibility}
   * (only marks terrain as explored, does not pierce CreatesShroud darkness).
   */
  readonly revealGeneratedShroud: boolean

  constructor(params: {
    instanceName?: string
    requiresCondition?: string
    minRange?: WDist
    range?: WDist
    maxHeightDelta?: number
    moveRecalculationThreshold?: WDist
    type?: VisibilityType
    validRelationships?: PlayerRelationship
    revealGeneratedShroud?: boolean
  } = {}) {
    super(params)
    this.validRelationships = params.validRelationships ?? PlayerRelationship.Ally
    this.revealGeneratedShroud = params.revealGeneratedShroud ?? true
  }
}

// ---------------------------------------------------------------------------
// RevealsShroud (对应 OpenRA RevealsShroud)
// ---------------------------------------------------------------------------

/** Reveals fog-of-war for allied players.
 *
 * OpenRA 对照: RevealsShroud : AffectsShroud
 *
 * When active, this trait reveals shroud (fog of war) for players that match
 * the {@link RevealsShroudInfo.validRelationships} mask. It is the primary
 * vision mechanism for units in the game.
 *
 * The revealGeneratedShroud flag controls whether this trait can pierce
 * through darkness generated by CreatesShroud (Gap Generator):
 * - true: Uses Visibility (removes shroud completely, reveals units)
 * - false: Uses PassiveVisibility (only marks terrain as explored)
 *
 * Most logic (projectedCells, tick, position tracking, lifecycle hooks)
 * is inherited from {@link AffectsShroud}.
 */
export class RevealsShroud
  extends AffectsShroud<RevealsShroudInfo>
  implements INotifyCreated
{
  /** Trait dictionary registration keys.
   *
   * OpenRA 对照: N/A (C# uses reflection; TS uses explicit string registration)
   */
  static readonly interfaces: string[] = [
    'ISync',
    'ITick',
    'INotifyAddedToWorld',
    'INotifyRemovedFromWorld',
    'INotifyCenterPositionChanged',
    'INotifyFinishedMoving',
    'INotifyCreated',
    'RevealsShroud',
    'AffectsShroud',
    'ConditionalTrait',
    'component',
  ]

  /** The source type to use when adding visibility cells.
   *
   * Determined once at construction time from
   * {@link RevealsShroudInfo.revealGeneratedShroud}.
   *
   * OpenRA 对照: RevealsShroud.type (readonly Shroud.SourceType)
   */
  private readonly _sourceType: SourceType

  /** Collected range percentage modifiers from IRevealsShroudModifier traits.
   *
   * OpenRA 对照: RevealsShroud.rangeModifiers (IEnumerable<int>)
   *
   * Populated in {@link created} after the actor is fully initialized.
   * Applied in the {@link range} getter via {@link applyPercentageModifiers}.
   */
  private _rangeModifiers: number[] = []

  constructor(info: RevealsShroudInfo) {
    super(info)

    this._sourceType = info.revealGeneratedShroud
      ? SourceType.Visibility
      : SourceType.PassiveVisibility
  }

  // -------------------------------------------------------------------------
  // INotifyCreated (对应 OpenRA Created)
  // -------------------------------------------------------------------------

  /** Collect range modifiers after the actor is fully initialized.
   *
   * OpenRA 对照: RevealsShroud.Created(Actor self)
   *
   * Queries the actor's trait dictionary for IRevealsShroudModifier traits
   * and collects their percentage modifier values. These are applied in the
   * {@link range} getter via {@link applyPercentageModifiers}.
   */
  created(self: IGameActor): void {
    // Collect IRevealsShroudModifier range modifiers.
    // SAFETY: traitsImplementing is optional on IGameActor but exists at
    // runtime on all real actor implementations via the trait dictionary.
    const traitAny = self as any
    const modifierTraits = traitAny.traitsImplementing?.('IRevealsShroudModifier') ?? []
    this._rangeModifiers = (modifierTraits as IRevealsShroudModifier[]).map(
      (m) => m.getRevealsShroudModifier(),
    )
  }

  // -------------------------------------------------------------------------
  // Abstract method implementations (对应 OpenRA overrides)
  // -------------------------------------------------------------------------

  /** Add visibility cells for a player.
   *
   * OpenRA 对照: RevealsShroud.AddCellsToPlayerShroud(Actor, Player, PPos[])
   *
   * Only reveals shroud if the relationship between the actor's owner and
   * the target player matches the configured validRelationships mask.
   * The source type (Visibility or PassiveVisibility) is determined at
   * construction time from {@link RevealsShroudInfo.revealGeneratedShroud}.
   */
  protected addCellsToPlayerShroud(
    self: IGameActor,
    player: Player,
    cells: readonly PPos[],
  ): void {
    const owner = self.owner as Player | undefined
    if (!owner) return

    const relationship = owner.relationshipWith(player)
    if (!PlayerRelationshipExts.hasRelationship(this.info.validRelationships, relationship)) {
      return
    }

    player.shroud.addSource(this, this._sourceType, cells)
  }

  /** Remove this actor's visibility from a player.
   *
   * OpenRA 对照: RevealsShroud.RemoveCellsFromPlayerShroud(Actor, Player)
   *
   * Removes the source unconditionally — relationship filtering only
   * applies when adding cells (matching OpenRA behavior).
   */
  protected removeCellsFromPlayerShroud(
    _self: IGameActor,
    player: Player,
  ): void {
    player.shroud.removeSource(this)
  }

  // -------------------------------------------------------------------------
  // Range (对应 OpenRA Range property override)
  // -------------------------------------------------------------------------

  /** Effective range when the trait is enabled.
   *
   * OpenRA 对照: RevealsShroud.Range
   *
   * Returns WDist.Zero when the trait was disabled in the previous tick.
   * Otherwise, applies IRevealsShroudModifier percentage modifiers to the
   * configured range via {@link applyPercentageModifiers}.
   */
  override get range(): WDist {
    if (this.cachedTraitDisabled) return WDist.Zero

    // NOTE: Only apply modifiers when there are actual modifiers to apply.
    // If no modifiers are registered, skip the applyPercentageModifiers call
    // to avoid unnecessary computation.
    if (this._rangeModifiers.length > 0) {
      const modified = applyPercentageModifiers(
        this.info.range.length,
        this._rangeModifiers,
      )
      return new WDist(modified)
    }

    return this.info.range
  }

  // -------------------------------------------------------------------------
  // Dispose
  // -------------------------------------------------------------------------

  override dispose(): void {
    this._rangeModifiers = []
    super.dispose()
  }
}
