/**
 * Playwright E2E Tests — TerrainSpriteLayer Batch Rendering
 *
 * Target: http://localhost:5173/test/ch02-rendering/batch-rendering/
 * Generated by: Kimi MCP (kimi CLI, 2026-06-22)
 *
 * 5 acceptance criteria + edge cases per README.md:
 *   1. Engine initialization (Babylon.js / WebGL)
 *   2. Dirty row update (only target row affected)
 *   3. Sheet switching (global color change)
 *   4. Map size scaling (8x8 → 64x64)
 *   5. Click interaction (instant feedback)
 */

import { test, expect } from '@playwright/test';
import * as path from 'path';

const PAGE_URL = 'http://localhost:5173/test/ch02-rendering/batch-rendering/';
const EVIDENCE_DIR = path.resolve(
  __dirname,
  '../../../../../../test-results/manual/ch02-rendering/batch-rendering/evidence'
);

function evidenceFile(name: string): string {
  return path.join(EVIDENCE_DIR, name);
}

// ---------------------------------------------------------------------------
// Test 1: Engine initialization
// ---------------------------------------------------------------------------
test('engine initialization — Babylon.js + WebGL + canvas', async ({ page }) => {
  await page.goto(PAGE_URL);

  // Wait for Babylon.js to initialize (canvas creation + engine info)
  await page.waitForSelector('#info-engine', { timeout: 15000 });

  // Verify engine info contains Babylon.js or WebGL
  const engineInfo = await page.locator('#info-engine').textContent();
  expect(engineInfo).toMatch(/Babylon\.js|WebGL/);

  // Verify GPU error overlay is hidden
  const gpuError = page.locator('#gpu-error');
  await expect(gpuError).toBeHidden();

  // Verify canvas exists in sandbox
  const canvas = page.locator('#sandbox canvas');
  await expect(canvas).toBeAttached();

  await page.screenshot({
    path: evidenceFile('screenshot-engine-init.png'),
    fullPage: true,
  });
});

// ---------------------------------------------------------------------------
// Test 2: Dirty row update — only target row affected
// ---------------------------------------------------------------------------
test('dirty row update — target row changes, dirty count = 1', async ({ page }) => {
  await page.goto(PAGE_URL);
  await page.waitForSelector('#info-engine', { timeout: 15000 });

  // Select gradient-columns terrain pattern and apply
  await page.locator('#terrain-pattern').selectOption('gradient-columns');
  await page.locator('#btn-apply-terrain').click();
  await page.waitForTimeout(1500);

  // Set update row slider to 3
  await page.locator('#update-row').evaluate((el: HTMLInputElement) => {
    el.value = '3';
    el.dispatchEvent(new Event('input', { bubbles: true }));
    el.dispatchEvent(new Event('change', { bubbles: true }));
  });
  // Verify slider value updated
  await expect(page.locator('#update-row-val')).toHaveText('3');

  // Select red color (#update-color is a <select>)
  await page.locator('#update-color').selectOption('#e94560');

  // Click update row button
  await page.locator('#btn-update-row').click();
  await page.waitForTimeout(800);

  // The commit clears dirty rows after upload, but the commit time should be recorded
  const commitTimeText = await page.locator('#stat-commit-time').textContent();
  expect(commitTimeText?.trim()).not.toBe('- ms');

  await page.screenshot({
    path: evidenceFile('screenshot-dirty-row.png'),
    fullPage: true,
  });
});

// ---------------------------------------------------------------------------
// Test 3: Sheet switching — global color change verified via slot count
// ---------------------------------------------------------------------------
test('sheet switching — slot count increments, global effect', async ({ page }) => {
  await page.goto(PAGE_URL);
  await page.waitForSelector('#info-engine', { timeout: 15000 });

  // Initial state: should have 1 sheet slot used
  const initialSlots = await page.locator('#stat-active-sheets').textContent();
  expect(initialSlots?.trim()).toBe('1 / 8');

  // Switch to Sheet 1
  await page.locator('#active-sheet').selectOption('1');
  await page.locator('#btn-switch-sheet').click();
  await page.waitForTimeout(1500);

  // Verify slot count increased to 2
  const afterSlots = await page.locator('#stat-active-sheets').textContent();
  expect(afterSlots?.trim()).toBe('2 / 8');

  await page.screenshot({
    path: evidenceFile('screenshot-sheet-switch.png'),
    fullPage: true,
  });

  // Switch to Sheet 2
  await page.locator('#active-sheet').selectOption('2');
  await page.locator('#btn-switch-sheet').click();
  await page.waitForTimeout(1000);

  // Verify slot count increased to 3
  const afterSlots2 = await page.locator('#stat-active-sheets').textContent();
  expect(afterSlots2?.trim()).toBe('3 / 8');

  // Switch back to Sheet 0 (should not increase slot count)
  await page.locator('#active-sheet').selectOption('0');
  await page.locator('#btn-switch-sheet').click();
  await page.waitForTimeout(1000);

  // Slot count should still be 3 (Sheet 0 was already in use)
  const afterSlots3 = await page.locator('#stat-active-sheets').textContent();
  expect(afterSlots3?.trim()).toBe('3 / 8');
});

// ---------------------------------------------------------------------------
// Test 4: Map size scaling — 8x8, 32x32, 64x64 verified
// ---------------------------------------------------------------------------
test('map size scaling — 64x64 shows 4096 tiles', async ({ page }) => {
  await page.goto(PAGE_URL);
  await page.waitForSelector('#info-engine', { timeout: 15000 });

  // Initial state: 16x16 = 256 tiles
  await expect(page.locator('#stat-map-size')).toHaveText('16x16');
  await expect(page.locator('#stat-tiles')).toHaveText('256');

  // Switch to 8x8
  await page.locator('#map-size').selectOption('8');
  await page.locator('#btn-apply-terrain').click();
  await page.waitForTimeout(1500);
  await expect(page.locator('#stat-map-size')).toHaveText('8x8');
  await expect(page.locator('#stat-tiles')).toHaveText('64');

  // Switch to 32x32
  await page.locator('#map-size').selectOption('32');
  await page.locator('#btn-apply-terrain').click();
  await page.waitForTimeout(2000);
  await expect(page.locator('#stat-map-size')).toHaveText('32x32');
  await expect(page.locator('#stat-tiles')).toHaveText('1024');

  // Switch to 64x64
  await page.locator('#map-size').selectOption('64');
  await page.locator('#btn-apply-terrain').click();
  await page.waitForTimeout(3000);
  await expect(page.locator('#stat-map-size')).toHaveText('64x64');
  await expect(page.locator('#stat-tiles')).toHaveText('4096');

  await page.screenshot({
    path: evidenceFile('screenshot-map-64.png'),
    fullPage: true,
  });
});

// ---------------------------------------------------------------------------
// Test 5: Click interaction — canvas click triggers feedback
// ---------------------------------------------------------------------------
test('click interaction — tile click triggers tooltip or dirty row', async ({ page }) => {
  await page.goto(PAGE_URL);
  await page.waitForSelector('#info-engine', { timeout: 15000 });

  const canvas = page.locator('#sandbox canvas');
  await expect(canvas).toBeAttached();

  const box = await canvas.boundingBox();
  expect(box).not.toBeNull();

  if (box) {
    // Click near center of canvas
    const centerX = box.x + box.width / 2;
    const centerY = box.y + box.height / 2;

    await page.mouse.click(centerX, centerY);
    await page.waitForTimeout(500);

    // Either tooltip should appear or dirty rows should change
    const tooltipVisible = await page.locator('#cell-tooltip').isVisible().catch(() => false);

    if (!tooltipVisible) {
      // Fallback: check stat-update-time and stat-commit-time changed
      const commitTime = await page.locator('#stat-commit-time').textContent();
      expect(commitTime?.trim()).not.toBe('- ms');
    }
  }

  await page.screenshot({
    path: evidenceFile('screenshot-click.png'),
    fullPage: true,
  });
});

// ---------------------------------------------------------------------------
// Test 6: Boundary row update — rows 0 and 15 (edge case)
// ---------------------------------------------------------------------------
test('boundary rows — update first and last row', async ({ page }) => {
  await page.goto(PAGE_URL);
  await page.waitForSelector('#info-engine', { timeout: 15000 });

  // Select stripes pattern for clear visual distinction
  await page.locator('#terrain-pattern').selectOption('stripes');
  await page.locator('#btn-apply-terrain').click();
  await page.waitForTimeout(1500);

  // Update row 0
  await page.locator('#update-row').evaluate((el: HTMLInputElement) => {
    el.value = '0';
    el.dispatchEvent(new Event('input', { bubbles: true }));
  });
  await page.locator('#update-color').selectOption('#3366ff'); // blue
  await page.locator('#btn-update-row').click();
  await page.waitForTimeout(800);

  const commitTime1 = await page.locator('#stat-commit-time').textContent();
  expect(commitTime1?.trim()).not.toBe('- ms');

  // Update row 15 (last row on 16x16 map)
  await page.locator('#update-row').evaluate((el: HTMLInputElement) => {
    el.value = '15';
    el.dispatchEvent(new Event('input', { bubbles: true }));
  });
  await page.locator('#update-color').selectOption('#ff9933'); // orange
  await page.locator('#btn-update-row').click();
  await page.waitForTimeout(800);

  const commitTime2 = await page.locator('#stat-commit-time').textContent();
  expect(commitTime2?.trim()).not.toBe('- ms');

  await page.screenshot({
    path: evidenceFile('screenshot-boundary-rows.png'),
    fullPage: true,
  });
});

// ---------------------------------------------------------------------------
// Test 7: Rapid random updates — 10 consecutive without crash
// ---------------------------------------------------------------------------
test('rapid random updates — 10 clicks, no crash, FPS display present', async ({ page }) => {
  await page.goto(PAGE_URL);
  await page.waitForSelector('#info-engine', { timeout: 15000 });

  for (let i = 0; i < 10; i++) {
    await page.locator('#btn-update-random-cell').click();
    await page.waitForTimeout(300);
  }

  // Verify engine is still running (no crash)
  const engineInfo = await page.locator('#info-engine').textContent();
  expect(engineInfo).toMatch(/Babylon\.js|WebGL/);

  // Verify FPS counter still exists and displays a number
  const fpsText = await page.locator('#info-fps').textContent();
  expect(fpsText?.trim()).toMatch(/^\d+$/);

  await page.screenshot({
    path: evidenceFile('screenshot-rapid-updates.png'),
    fullPage: true,
  });
});
