// @ts-nocheck — AUTO-GENERATED by utils/sync-hash-generator.ts. DO NOT EDIT.
/* eslint-disable */
/**
 * sync-hashes.generated.ts — pre-generated computeSyncHash() functions
 * for all ISync classes discovered by scanning src for @VerifySync fields.
 *
 * Regenerate: npx tsx utils/sync-hash-generator.ts
 *
 * OpenRA 对照: OpenRA.Game/Sync.cs GenerateHashFunc IL emission
 */

import { hashCombine, hashCombine3, registerSyncHash, type ISync }
  from './Sync'
import {
  HashInt2, HashCPos, HashCVec, HashWDist,
  HashWPos, HashWVec, HashWAngle, HashWRot,
  HashActor, HashPlayer, HashTarget,
} from './Sync'
// Import lookupSyncHash for nested ISync field hashing.
// The Sync module exports it; generated code uses it via hashNested().
import { Sync } from './Sync'


// No ISync classes with @VerifySync fields found in src/ directory.