/**
 * sync-hashes.generated.ts — AUTO-GENERATED by utils/sync-hash-generator.ts
 * DO NOT EDIT MANUALLY.
 *
 * Contains pre-generated computeSyncHash() functions for all ISync classes
 * discovered by scanning src/**/*.ts for @VerifySync JSDoc tags.
 *
 * Regenerate: npx tsx utils/sync-hash-generator.ts
 *
 * OpenRA 对照: OpenRA.Game/Sync.cs GenerateHashFunc IL emission
 */
/* eslint-disable */
/* @ts-nocheck */

import { hashCombine, hashCombine3, registerSyncHash, type ISync }
  from './Sync'
import {
  HashInt2, HashCPos, HashCVec, HashWDist,
  HashWPos, HashWVec, HashWAngle, HashWRot,
  HashActor, HashPlayer, HashTarget,
} from './Sync'


// No ISync classes with @VerifySync fields found in src/ directory.