/**
 * Playwright acceptance test: ch03-actor-system / player-diplomacy
 *
 * Tests Player system ARGB color rendering, relationship color mapping,
 * viewer switching, stance color toggle, random relations, and panel
 * information completeness.
 *
 * Generated by: Kimi MCP (kimi_agent) + acceptance-test-runner
 * Date: 2026-06-22
 */

import { test, expect } from '@playwright/test';
import * as path from 'path';
import * as fs from 'fs';

const BASE_URL = 'http://localhost:5173/test/ch03-actor-system/player-diplomacy/';
const EVIDENCE_DIR = 'test-results/manual/ch03-actor-system/player-diplomacy/evidence';

function evidenceFile(name: string): string {
  const dir = path.resolve(EVIDENCE_DIR);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }
  return path.join(dir, name);
}

// ---------------------------------------------------------------------------
// Helper utilities
// ---------------------------------------------------------------------------

/** Wait for Babylon.js scene to initialize (canvas present, engine detected, FPS running) */
async function waitForScene(page: any): Promise<void> {
  await page.waitForSelector('#canvas-panel canvas', { timeout: 15000 });
  await page.waitForFunction(() => {
    const el = document.getElementById('info-engine');
    const text = el?.textContent || '';
    return text.includes('Babylon.js') || text.includes('WebGL');
  }, { timeout: 10000 });
  // Wait for FPS counter to show a number
  await page.waitForFunction(() => {
    const text = document.getElementById('info-fps')?.textContent;
    return text !== null && text !== undefined && /^\d+$/.test(text.trim());
  }, { timeout: 10000 });
}

/** Extract the 8-char hex from an ARGB string like "0xFF3399F2" */
function normalizeArgbHex(input: string): string {
  const m = input.match(/0x([0-9A-Fa-f]{8})/);
  if (m) return m[1].toUpperCase();
  // Fallback: strip non-hex
  const hex = input.replace(/[^0-9A-Fa-f]/g, '').toUpperCase();
  return hex.length >= 8 ? hex.slice(0, 8) : hex;
}

/** Convert 8-char ARGB hex to 6-char RGB hex (drop alpha) */
function argbToRgbHex(argb8: string): string {
  return argb8.length >= 8 ? argb8.substring(2).toUpperCase() : argb8.toUpperCase();
}

/** Convert a CSS computed color (rgb(r,g,b) / #rrggbb) to 6-char uppercase hex */
async function cssColorToRgbHex(rgb: string): Promise<string> {
  rgb = rgb.trim();
  if (rgb.startsWith('#')) {
    return rgb.replace('#', '').toUpperCase().padStart(6, '0');
  }
  const m = rgb.match(/rgba?\s*\(\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)/i);
  if (m) {
    return [m[1], m[2], m[3]]
      .map(v => parseInt(v, 10).toString(16).padStart(2, '0').toUpperCase())
      .join('');
  }
  return '000000';
}

/** Euclidean distance between two 6-char RGB hex strings */
function hexDistance(a: string, b: string): number {
  const ha = a.padStart(6, '0');
  const hb = b.padStart(6, '0');
  const r1 = parseInt(ha.substring(0, 2), 16);
  const g1 = parseInt(ha.substring(2, 4), 16);
  const b1 = parseInt(ha.substring(4, 6), 16);
  const r2 = parseInt(hb.substring(0, 2), 16);
  const g2 = parseInt(hb.substring(2, 4), 16);
  const b2 = parseInt(hb.substring(4, 6), 16);
  return Math.sqrt(Math.pow(r1 - r2, 2) + Math.pow(g1 - g2, 2) + Math.pow(b1 - b2, 2));
}

// ---- DOM helper functions ----

async function getViewerName(page: any): Promise<string> {
  return (await page.locator('#viewer-label').textContent())?.trim() || '';
}

async function getRowName(page: any, idx: number): Promise<string> {
  return (await page.locator('.color-row').nth(idx).locator('.color-meta .name').textContent())?.trim() || '';
}

async function getRowOriginalArgb(page: any, idx: number): Promise<string> {
  return (await page.locator('.color-row').nth(idx).locator('.argb').first().textContent())?.trim() || '';
}

async function getRowDisplayArgb(page: any, idx: number): Promise<string> {
  const texts = await page.locator('.color-row').nth(idx).locator('.argb').allTextContents();
  return texts.find(t => t.includes('显示:')) || texts[1] || '';
}

async function getRowRelationshipClass(page: any, idx: number): Promise<string> {
  const cls = await page.locator('.color-row').nth(idx).evaluate((el: HTMLElement) => el.className);
  if (cls.includes('self')) return 'self';
  if (cls.includes('enemy')) return 'enemy';
  if (cls.includes('ally')) return 'ally';
  if (cls.includes('neutral')) return 'neutral';
  return 'unknown';
}

async function getSwatchRgbHex(page: any, idx: number): Promise<string> {
  const style = await page.locator('.color-row').nth(idx).locator('.swatch').evaluate((el: HTMLElement) => {
    return window.getComputedStyle(el).backgroundColor;
  });
  return cssColorToRgbHex(style);
}

/** Get relationship grid cell text for a given row (0=header, 1-5 = player rows) and column */
async function getGridCellText(page: any, row: number, col: number): Promise<string> {
  // Grid is flat: 6 cols per row. Skip header row (row 0) to get data rows.
  const cellsPerRow = 6;
  const flatIdx = row * cellsPerRow + col;
  const cell = page.locator('#rel-grid > div').nth(flatIdx);
  return (await cell.textContent())?.trim() || '';
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

test.describe('Ch03 Actor System - Player Diplomacy', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(BASE_URL);
    await waitForScene(page);
    // Extra settle time for full render + FPS stabilization
    await page.waitForTimeout(3000);
  });

  // -----------------------------------------------------------------------
  // Test 1: Original ARGB colors render correctly
  // -----------------------------------------------------------------------
  test('test-1: player original ARGB colors render correctly', async ({ page }) => {
    const stanceCheckbox = page.locator('#chk-stance-colors');
    await expect(stanceCheckbox).toBeChecked();
    await stanceCheckbox.uncheck();
    await page.waitForTimeout(500);
    await expect(stanceCheckbox).not.toBeChecked();

    await page.screenshot({ path: evidenceFile('screenshot-1-original-colors.png'), fullPage: true });

    const expected = [
      { name: 'Player A', argb: '0xFF3399F2', rgb: '3399F2' },
      { name: 'Player B', argb: '0xFFF25433', rgb: 'F25433' },
      { name: 'Player C', argb: '0xFF33CC66', rgb: '33CC66' },
      { name: 'Player D', argb: '0xFFFF9933', rgb: 'FF9933' },
      { name: 'Neutral',  argb: '0xFFB0B0B0', rgb: 'B0B0B0' },
    ];

    const rowCount = await page.locator('.color-row').count();
    expect(rowCount, 'color panel should have 5 rows').toBe(5);

    for (let i = 0; i < expected.length; i++) {
      const exp = expected[i];

      // Name check
      const name = await getRowName(page, i);
      expect(name, `row ${i} name should contain ${exp.name}`).toContain(exp.name);

      // Original ARGB
      const origText = await getRowOriginalArgb(page, i);
      expect(origText, `row ${i} original ARGB should contain ${exp.argb}`).toContain(exp.argb);

      // Display ARGB should match original (stance disabled)
      const displayText = await getRowDisplayArgb(page, i);
      expect(displayText, `row ${i} display ARGB should contain ${exp.argb} (stance disabled)`).toContain(exp.argb);

      // Swatch color distance
      const swatchHex = await getSwatchRgbHex(page, i);
      const dist = hexDistance(swatchHex, exp.rgb);
      expect(dist, `row ${i} ${exp.name}: swatch ${swatchHex} vs expected ${exp.rgb} (dist=${dist.toFixed(1)}, limit=10)`)
        .toBeLessThanOrEqual(10);
    }
  });

  // -----------------------------------------------------------------------
  // Test 2: Relationship color mapping correct (viewer = Player A)
  // -----------------------------------------------------------------------
  test('test-2: relationship color mapping is correct for viewer A', async ({ page }) => {
    const stanceCheckbox = page.locator('#chk-stance-colors');
    await expect(stanceCheckbox).toBeChecked();

    const viewer = await getViewerName(page);
    expect(viewer, 'initial viewer should be Player A').toContain('Player A');

    await page.screenshot({ path: evidenceFile('screenshot-2-stance-colors-viewer-a.png'), fullPage: true });

    const expected = [
      { name: 'Player A', rel: 'self',   argb: '0xFF00FF00', rgb: '00FF00' },
      { name: 'Player B', rel: 'enemy',  argb: '0xFFFF0000', rgb: 'FF0000' },
      { name: 'Player C', rel: 'ally',   argb: '0xFFFFFF00', rgb: 'FFFF00' },
      { name: 'Player D', rel: 'neutral', argb: '0xFFFFFFFF', rgb: 'FFFFFF' },
      { name: 'Neutral',  rel: 'neutral', argb: '0xFFFFFFFF', rgb: 'FFFFFF' },
    ];

    for (let i = 0; i < expected.length; i++) {
      const exp = expected[i];
      const row = page.locator('.color-row').nth(i);

      // CSS relationship class
      await expect(row, `row ${i} should have class "${exp.rel}"`).toHaveClass(new RegExp(`\\b${exp.rel}\\b`));

      // Name
      const name = await getRowName(page, i);
      expect(name, `row ${i} name should contain ${exp.name}`).toContain(exp.name);

      // Relationship class from helper
      const relClass = await getRowRelationshipClass(page, i);
      expect(relClass, `row ${i} relationship should be ${exp.rel}`).toBe(exp.rel);

      // Display ARGB
      const displayText = await getRowDisplayArgb(page, i);
      expect(displayText, `row ${i} display ARGB should contain ${exp.argb}`).toContain(exp.argb);

      // Swatch color (allow tolerance for white/neutral since #FFFFFF exact match in CSS)
      const swatchHex = await getSwatchRgbHex(page, i);
      const dist = hexDistance(swatchHex, exp.rgb);
      expect(dist, `row ${i} ${exp.name}: stance swatch ${swatchHex} vs ${exp.rgb} (dist=${dist.toFixed(1)})`)
        .toBeLessThanOrEqual(10);
    }
  });

  // -----------------------------------------------------------------------
  // Test 3: Viewer switching changes relationship colors
  // -----------------------------------------------------------------------
  test('test-3: viewer switching changes relationship colors', async ({ page }) => {
    const stanceCheckbox = page.locator('#chk-stance-colors');
    await expect(stanceCheckbox).toBeChecked();

    // Reset to known state
    await page.click('#btn-reset');
    await page.waitForTimeout(500);
    await expect(stanceCheckbox).toBeChecked();

    const viewers = ['Player A', 'Player B', 'Player C', 'Player D', 'Neutral'];

    for (let cycle = 0; cycle < viewers.length; cycle++) {
      if (cycle > 0) {
        await page.click('#btn-cycle-viewer');
        await page.waitForTimeout(500);
      }

      const currentViewer = await getViewerName(page);
      expect(currentViewer, `viewer after ${cycle} cycles should be ${viewers[cycle]}`).toContain(viewers[cycle]);

      await page.screenshot({
        path: evidenceFile(`screenshot-3-viewer-${viewers[cycle].toLowerCase().replace(' ', '-')}.png`),
        fullPage: true,
      });

      // Self row should be Self
      const selfRel = await getRowRelationshipClass(page, cycle);
      expect(selfRel, `viewer=${viewers[cycle]}: self row should be "self"`).toBe('self');
    }

    // Specific: viewer B assertions
    // Reset and cycle to B
    await page.click('#btn-reset');
    await page.waitForTimeout(500);
    await page.click('#btn-cycle-viewer');
    await page.waitForTimeout(500);
    expect(await getViewerName(page)).toContain('Player B');

    // A should be Enemy to B
    const relA = await getRowRelationshipClass(page, 0);
    expect(relA, 'viewer B: Player A should be Enemy').toBe('enemy');

    // D should be Ally to B
    const relD = await getRowRelationshipClass(page, 3);
    expect(relD, 'viewer B: Player D should be Ally').toBe('ally');

    // Cycle to Neutral: all non-self should be Neutral
    while (!(await getViewerName(page)).includes('Neutral')) {
      await page.click('#btn-cycle-viewer');
      await page.waitForTimeout(300);
    }
    expect(await getViewerName(page)).toContain('Neutral');

    for (let i = 0; i < 4; i++) {
      const rel = await getRowRelationshipClass(page, i);
      expect(rel, `viewer Neutral: row ${i} should be Neutral`).toBe('neutral');
    }

    await page.screenshot({ path: evidenceFile('screenshot-3-viewer-neutral-verified.png'), fullPage: true });
  });

  // -----------------------------------------------------------------------
  // Test 4: Disabling stance colors restores original colors
  // -----------------------------------------------------------------------
  test('test-4: disabling stance colors restores original colors', async ({ page }) => {
    const stanceCheckbox = page.locator('#chk-stance-colors');

    // Reset to known state
    await page.click('#btn-reset');
    await page.waitForTimeout(500);
    await expect(stanceCheckbox).toBeChecked();

    // Uncheck stance colors
    await stanceCheckbox.uncheck();
    await page.waitForTimeout(500);
    await expect(stanceCheckbox).not.toBeChecked();

    await page.screenshot({ path: evidenceFile('screenshot-4-stance-disabled.png'), fullPage: true });

    const expectedOriginal = [
      { name: 'Player A', rgb: '3399F2' },
      { name: 'Player B', rgb: 'F25433' },
      { name: 'Player C', rgb: '33CC66' },
      { name: 'Player D', rgb: 'FF9933' },
      { name: 'Neutral',  rgb: 'B0B0B0' },
    ];

    const swatches: string[] = [];

    for (let i = 0; i < expectedOriginal.length; i++) {
      const exp = expectedOriginal[i];
      const row = page.locator('.color-row').nth(i);

      // Desc should say stance disabled
      const desc = await row.locator('.desc').textContent();
      expect(desc || '', `row ${i} desc should indicate original colors`).toContain('关系色禁用');

      // Display ARGB should match original ARGB
      const origHex = normalizeArgbHex(await getRowOriginalArgb(page, i));
      const displayHex = normalizeArgbHex(await getRowDisplayArgb(page, i));
      expect(displayHex, `row ${i} display ARGB (${displayHex}) should match original (${origHex})`).toBe(origHex);

      // Swatch color
      const swatchHex = await getSwatchRgbHex(page, i);
      swatches.push(swatchHex);
      const dist = hexDistance(swatchHex, exp.rgb);
      expect(dist, `row ${i} ${exp.name}: disabled swatch ${swatchHex} vs ${exp.rgb} (dist=${dist.toFixed(1)})`)
        .toBeLessThanOrEqual(10);
    }

    // All 5 original colors should be distinct
    const unique = new Set(swatches);
    expect(unique.size, `all 5 original swatch colors should be distinct (got ${unique.size} unique: ${[...swatches].join(', ')})`)
      .toBe(5);
  });

  // -----------------------------------------------------------------------
  // Test 5: Random relations work correctly
  // -----------------------------------------------------------------------
  test('test-5: random relations work correctly', async ({ page }) => {
    const stanceCheckbox = page.locator('#chk-stance-colors');
    await expect(stanceCheckbox).toBeChecked();

    // Reset to known state
    await page.click('#btn-reset');
    await page.waitForTimeout(500);

    // Snapshot initial relationships from DOM rows
    const getRowRelClasses = async () => {
      const rels: string[] = [];
      for (let i = 0; i < 5; i++) {
        rels.push(await getRowRelationshipClass(page, i));
      }
      return rels;
    };

    const initialRels = await getRowRelClasses();
    const seenRels = new Set<string>();
    let relsChanged = false;

    for (let click = 0; click < 6; click++) {
      await page.click('#btn-random-relations');
      await page.waitForTimeout(500);

      const currentRels = await getRowRelClasses();

      // Collect all non-self relationships for coverage check
      for (const r of currentRels) {
        if (r !== 'unknown') seenRels.add(r);
      }

      // Check if relations changed from initial
      if (!relsChanged && JSON.stringify(currentRels) !== JSON.stringify(initialRels)) {
        relsChanged = true;
      }

      // Self diagonal: viewer row's own cell should always be "self"
      const viewerName = await getViewerName(page);
      // Find which row corresponds to the viewer
      const rowNames = await Promise.all([0, 1, 2, 3, 4].map(i => getRowName(page, i)));
      const viewerIdx = rowNames.findIndex(n => viewerName.includes(n.split(' ')[0]?.replace('(', '').trim() || ''));
      if (viewerIdx >= 0) {
        expect(currentRels[viewerIdx], `click ${click}: viewer self-row should be Self`).toBe('self');
      }

      await page.screenshot({ path: evidenceFile(`screenshot-5-random-${click + 1}.png`), fullPage: true });
    }

    // Relations should have changed at least once
    expect(relsChanged, 'relationship data should change after random clicks').toBe(true);

    // All non-self relations should appear
    expect(seenRels.has('self'), 'Self should appear in random relations').toBe(true);
    expect(seenRels.has('ally'), 'Ally should appear in random relations').toBe(true);
    expect(seenRels.has('neutral'), 'Neutral should appear in random relations').toBe(true);
    expect(seenRels.has('enemy'), 'Enemy should appear in random relations').toBe(true);
  });

  // -----------------------------------------------------------------------
  // Test 6: Color panel information completeness
  // -----------------------------------------------------------------------
  test('test-6: color panel information completeness', async ({ page }) => {
    await page.click('#btn-reset');
    await page.waitForTimeout(500);

    await page.screenshot({ path: evidenceFile('screenshot-6-panel-completeness.png'), fullPage: true });

    const rows = await page.locator('.color-row').all();
    expect(rows.length, 'color panel should contain 5 rows').toBe(5);

    for (let i = 0; i < rows.length; i++) {
      const row = rows[i];

      // Name is present
      const nameText = (await row.locator('.color-meta .name').textContent())?.trim() || '';
      expect(nameText, `row ${i} should have a name`).not.toBe('');

      // At least 2 .argb elements (original + display)
      const argbCount = await row.locator('.argb').count();
      expect(argbCount, `row ${i} should have >= 2 ARGB fields`).toBeGreaterThanOrEqual(2);

      // Original ARGB format: "原始: 0xXXXXXXXX"
      const origText = await getRowOriginalArgb(page, i);
      expect(origText, `row ${i} original ARGB format`).toMatch(/原始:\s*0x[0-9A-Fa-f]{8}/);

      // Display ARGB format: "显示: 0xXXXXXXXX"
      const displayText = await getRowDisplayArgb(page, i);
      expect(displayText, `row ${i} display ARGB format`).toMatch(/显示:\s*0x[0-9A-Fa-f]{8}/);

      // Swatch has a valid CSS color
      const swatchColor = await row.locator('.swatch').evaluate((el: HTMLElement) =>
        window.getComputedStyle(el).backgroundColor
      );
      expect(swatchColor, `row ${i} swatch should have a background color`).toMatch(/rgba?\(|^#/);

      // Has a relationship CSS class
      const cls = await row.evaluate((el: HTMLElement) => el.className);
      const hasRel = /\b(self|ally|neutral|enemy)\b/.test(cls);
      expect(hasRel, `row ${i} should have a relationship CSS class`).toBe(true);
    }

    // Verify relationship grid exists and has content
    const gridCells = await page.locator('#rel-grid > div').count();
    expect(gridCells, 'relationship grid should have cells').toBeGreaterThan(10);

    // Verify grid has marker (▶) on current viewer row (Player A = row 1 after header)
    const rowAFirstCell = await getGridCellText(page, 1, 0);
    // Row-hdr cell shows "A" as label, but the relation cells start at col 1
    // The marker ▶ appears in relation cells for non-self columns
    // Check some cell in viewer's row has ▶
    let hasMarker = false;
    for (let col = 1; col <= 5; col++) {
      const cellText = await getGridCellText(page, 1, col);
      if (cellText.includes('▶')) {
        hasMarker = true;
        break;
      }
    }
    expect(hasMarker, 'viewer row should have ▶ markers on non-self cells').toBe(true);

    // Verify swatch colors match display ARGB (within tolerance)
    for (let i = 0; i < rows.length; i++) {
      const displayText = await getRowDisplayArgb(page, i);
      const argb8 = normalizeArgbHex(displayText);
      const expectedRgb = argbToRgbHex(argb8);
      const swatchHex = await getSwatchRgbHex(page, i);
      const dist = hexDistance(swatchHex, expectedRgb);
      expect(dist, `row ${i} swatch ${swatchHex} should match display ARGB RGB ${expectedRgb} (dist=${dist.toFixed(1)})`)
        .toBeLessThanOrEqual(10);
    }
  });

  // -----------------------------------------------------------------------
  // Edge case: Reset restores initial state
  // -----------------------------------------------------------------------
  test('edge: reset restores initial state', async ({ page }) => {
    // Change state
    await page.click('#btn-random-relations');
    await page.waitForTimeout(300);
    await page.click('#btn-cycle-viewer');
    await page.waitForTimeout(300);
    await page.locator('#chk-stance-colors').uncheck();
    await page.waitForTimeout(300);

    // Reset
    await page.click('#btn-reset');
    await page.waitForTimeout(500);

    // Verify: viewer = Player A, stance ON, original relation matrix
    expect(await getViewerName(page)).toContain('Player A');
    await expect(page.locator('#chk-stance-colors')).toBeChecked();

    // Original relationship: A-Self, B-Enemy, C-Ally, D-Neutral, Neutral-Neutral
    expect(await getRowRelationshipClass(page, 0)).toBe('self');
    expect(await getRowRelationshipClass(page, 1)).toBe('enemy');
    expect(await getRowRelationshipClass(page, 2)).toBe('ally');
    expect(await getRowRelationshipClass(page, 3)).toBe('neutral');
    expect(await getRowRelationshipClass(page, 4)).toBe('neutral');
  });

  // -----------------------------------------------------------------------
  // Edge case: rapid viewer cycling does not crash
  // -----------------------------------------------------------------------
  test('edge: rapid viewer cycling is stable', async ({ page }) => {
    await page.click('#btn-reset');
    await page.waitForTimeout(500);

    // Click cycle 10 times rapidly
    for (let i = 0; i < 10; i++) {
      await page.click('#btn-cycle-viewer');
      await page.waitForTimeout(100);
    }

    // Should still render (check canvas exists and FPS is positive)
    const canvas = page.locator('#canvas-panel canvas');
    await expect(canvas).toBeVisible();

    // Color panel should have 5 rows (not corrupted)
    await expect(page.locator('.color-row')).toHaveCount(5);

    // Viewer label should show a valid player name
    const viewer = await getViewerName(page);
    expect(viewer).toBeTruthy();
  });
});
