/**
 * sync-hash-generator.ts — Build-time scanner and code generator for ISync classes
 * OpenRA 对照: OpenRA.Game/Sync.cs GenerateHashFunc (Reflection.Emit IL gen)
 *
 * 核心范式转换:
 * - C# Reflection.Emit DynamicMethod IL generation → TypeScript compiler API AST
 *   scanning + JavaScript code generation
 * - C# runtime [VerifySync] attribute discovery → build-time AST scan for
 *   `@VerifySync` JSDoc tags on class properties
 * - C# IL opcodes (Ldfld, Call, Xor) → emitted `hashCombine()` call chain
 * - C# ConcurrentCache auto-population → generated file self-registers via
 *   `registerSyncHash()` at import time
 *
 * Usage:
 *   npx tsx utils/sync-hash-generator.ts
 *   (or as a Vite plugin: import { syncHashVitePlugin } from '...')
 *
 * Scans for:
 *   class Foo implements ISync {
 *     /** @VerifySync *`/` health: number = 100
 *     /** @VerifySync *`/` ammo: number = 50
 *   }
 *
 * Generates:
 *   computeSyncHash_Foo(obj: Foo): number { ... }
 *   registerSyncHash('Foo', computeSyncHash_Foo as (obj: ISync) => number)
 */

import * as ts from 'typescript'
import * as fs from 'node:fs'
import * as path from 'node:path'

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

/**
 * Metadata for a single @VerifySync-marked field.
 */
interface SyncFieldInfo {
  /** The field name (e.g., "health"). */
  name: string
  /** The TypeScript type name as written in source (e.g., "number", "CPos"). */
  typeName: string
  /** Whether the type is `number | null` or similar. */
  isNullable: boolean
  /** Whether the type name matches a known custom hash function type. */
  customHashType: string | null
}

/**
 * Metadata for a discovered ISync class.
 */
interface SyncClassInfo {
  /** The class name (e.g., "Health"). */
  className: string
  /** The module import path (relative to src/OpenRA.Game/). */
  modulePath: string
  /** All @VerifySync-marked fields in declaration order. */
  fields: SyncFieldInfo[]
}

// ---------------------------------------------------------------------------
// Constants
// ---------------------------------------------------------------------------

/**
 * Type names that have known custom hash functions.
 * Maps TypeScript type name → custom hash function name used in generated code.
 *
 * NOTE: These are the type names as they appear in TypeScript source.
 * The hash function prefix is always "Hash".
 */
const CUSTOM_HASH_TYPES: ReadonlyMap<string, string> = new Map([
  ['int2', 'HashInt2'],
  ['CPos', 'HashCPos'],
  ['CVec', 'HashCVec'],
  ['WDist', 'HashWDist'],
  ['WPos', 'HashWPos'],
  ['WVec', 'HashWVec'],
  ['WAngle', 'HashWAngle'],
  ['WRot', 'HashWRot'],
  ['Actor', 'HashActor'],
  ['Player', 'HashPlayer'],
  ['Target', 'HashTarget'],
])

/**
 * Primitive types that can be hashed by combining the value directly.
 */
const PRIMITIVE_HASH_TYPES: ReadonlySet<string> = new Set([
  'number',
  'boolean',
])

/**
 * Template for the generated file header.
 */
const GENERATED_FILE_HEADER = `/**
 * sync-hashes.generated.ts — AUTO-GENERATED by utils/sync-hash-generator.ts
 * DO NOT EDIT MANUALLY.
 *
 * Contains pre-generated computeSyncHash() functions for all ISync classes
 * discovered by scanning src/**\/*.ts for @VerifySync JSDoc tags.
 *
 * Regenerate: npx tsx utils/sync-hash-generator.ts
 *
 * OpenRA 对照: OpenRA.Game/Sync.cs GenerateHashFunc IL emission
 */
/* eslint-disable */
/* @ts-nocheck */

import { hashCombine, hashCombine3, registerSyncHash, type ISync }
  from './Sync'
import {
  HashInt2, HashCPos, HashCVec, HashWDist,
  HashWPos, HashWVec, HashWAngle, HashWRot,
  HashActor, HashPlayer, HashTarget,
} from './Sync'
`

// ---------------------------------------------------------------------------
// AST Scanner
// ---------------------------------------------------------------------------

/**
 * Check if a class declaration has `ISync` in its implements clause
 * or referenced via heritageClauses.
 */
function classImplementsISync(node: ts.ClassDeclaration): boolean {
  const heritage = node.heritageClauses
  if (!heritage) return false

  for (const clause of heritage) {
    if (clause.token === ts.SyntaxKind.ImplementsKeyword) {
      for (const type of clause.types) {
        // Check for "ISync" (possibly qualified: "Sync.ISync")
        const typeText = type.expression.getText()
        if (typeText === 'ISync' || typeText.endsWith('.ISync')) {
          return true
        }
      }
    }
  }
  return false
}

/**
 * Extract JSDoc tags from a node's leading comments.
 * Returns true if the node has a `@VerifySync` tag in its JSDoc.
 */
function hasVerifySyncTag(node: ts.Node): boolean {
  const sourceFile = node.getSourceFile()
  const fullText = sourceFile.getFullText()

  // Get the leading comment ranges for this node
  const commentRanges = ts.getLeadingCommentRanges(fullText, node.getFullStart())
  if (!commentRanges) return false

  for (const range of commentRanges) {
    const commentText = fullText.slice(range.pos, range.end)
    // Check for @VerifySync in the comment
    if (/@VerifySync\b/.test(commentText)) {
      return true
    }
  }
  return false
}

/**
 * Determine if a type name is nullable (ends with `| null` or `| null | undefined`).
 * Extracts the underlying type name for custom hash lookup.
 */
function analyzeType(typeNode: ts.TypeNode | undefined): {
  typeName: string
  isNullable: boolean
  customHashType: string | null
} {
  if (!typeNode) {
    return { typeName: 'any', isNullable: false, customHashType: null }
  }

  const fullText = typeNode.getText()
  const isNullable = fullText.includes('| null')

  // Extract the base type name (before any `| null`)
  let baseTypeName = fullText
  if (fullText.includes('|')) {
    // Take the first part before |
    baseTypeName = fullText.split('|')[0].trim()
    // If it's "null | Type" pattern, take the second part
    if (baseTypeName === 'null') {
      const parts = fullText.split('|')
      baseTypeName = (parts[1] ?? parts[0]).trim()
    }
  }

  // Check if the base type is a custom hash type
  const customHashType = CUSTOM_HASH_TYPES.get(baseTypeName) ?? null

  return {
    typeName: fullText,
    isNullable,
    customHashType,
  }
}

/**
 * Scan a single TypeScript source file for ISync classes.
 *
 * @param filePath — absolute path to the .ts file
 * @returns discovered sync class info (empty array if none)
 */
function scanSourceFile(filePath: string): SyncClassInfo[] {
  const content = fs.readFileSync(filePath, 'utf-8')
  const sourceFile = ts.createSourceFile(
    filePath,
    content,
    ts.ScriptTarget.ESNext,
    /* setParentNodes */ true,
  )

  const classes: SyncClassInfo[] = []

  function visit(node: ts.Node): void {
    if (ts.isClassDeclaration(node) && node.name) {
      if (classImplementsISync(node)) {
        const fields: SyncFieldInfo[] = []

        for (const member of node.members) {
          if (ts.isPropertyDeclaration(member) && member.name) {
            if (hasVerifySyncTag(member)) {
              const fieldName = member.name.getText()
              const { typeName, isNullable, customHashType } = analyzeType(
                member.type,
              )
              fields.push({
                name: fieldName,
                typeName,
                isNullable,
                customHashType,
              })
            }
          }
        }

        if (fields.length > 0) {
          // Compute relative module path
          const relPath = path.relative(
            path.resolve(process.cwd(), 'src/OpenRA.Game'),
            filePath,
          )
          const modulePath = relPath.replace(/\\/g, '/').replace(/\.ts$/, '')

          classes.push({
            className: node.name.getText(),
            modulePath: './' + modulePath,
            fields,
          })
        }
      }
    }
    ts.forEachChild(node, visit)
  }

  visit(sourceFile)
  return classes
}

// ---------------------------------------------------------------------------
// Code Emitter
// ---------------------------------------------------------------------------

/**
 * Generate the hash expression for a single sync field.
 *
 * @param field — the field metadata
 * @param objExpr — JS expression for accessing the object (e.g., "obj")
 * @returns JS expression string computing the field's hash
 */
function emitFieldHash(field: SyncFieldInfo, objExpr: string): string {
  const accessor = `${objExpr}.${field.name}`
  const nullGuard = field.isNullable

  if (field.customHashType) {
    // Custom hash type: HashCPos(obj.field), HashWPos(obj.field), etc.
    const hashFn = field.customHashType
    if (nullGuard) {
      // Nullable custom type:
      // For types where null maps to 0 (Actor, Player): HashActor(field)
      // For coordinate types: field !== null ? HashWPos(field) : 0
      if (
        hashFn === 'HashActor' ||
        hashFn === 'HashPlayer'
      ) {
        return `${hashFn}(${accessor} as any)`
      }
      return `(${accessor} !== null ? ${hashFn}(${accessor}) : 0)`
    }
    // For Target, hashFn handles the switch internally, never null
    return `${hashFn}(${accessor} as any)`
  }

  if (field.typeName === 'number') {
    if (nullGuard) {
      return `(${accessor} !== null ? ${accessor} | 0 : 0)`
    }
    return `${accessor} | 0`
  }

  if (field.typeName === 'boolean') {
    if (nullGuard) {
      return `(${accessor} !== null ? (${accessor} ? 0x555 : 0xaaa) : 0)`
    }
    return `(${accessor} ? 0x555 : 0xaaa)`
  }

  // Unknown type — fall through to Sync.hash for ISync nested objects.
  // Check if the type name matches an ISync interface.
  if (nullGuard) {
    return `(${accessor} !== null ? hashNested(${accessor} as ISync) : 0)`
  }
  return `hashNested(${accessor} as ISync)`
}

/**
 * Generate a computeSyncHash function for a single class.
 */
function emitHashFunction(info: SyncClassInfo): string {
  const funcName = `computeSyncHash_${info.className}`
  const lines: string[] = []

  lines.push(`/**`)
  lines.push(` * Pre-generated sync hash for ${info.className}.`)
  lines.push(` *`)
  lines.push(` * OpenRA 对照: Sync.GenerateHashFunc(typeof(${info.className}))`)
  lines.push(` * Fields: ${info.fields.map((f) => f.name).join(', ')}`)
  lines.push(` */`)
  lines.push(
    `function ${funcName}(obj: any): number {`,
  )

  if (info.fields.length === 0) {
    lines.push(`  return 0`)
  } else {
    lines.push(`  let __hash = 0`)
    for (const field of info.fields) {
      const fieldExpr = emitFieldHash(field, 'obj')
      lines.push(`  __hash = hashCombine(__hash, ${fieldExpr})`)
    }
    lines.push(`  return __hash`)
  }

  lines.push(`}`)

  return lines.join('\n')
}

/**
 * Generate the complete contents of sync-hashes.generated.ts.
 *
 * @param classes — all discovered ISync classes
 * @returns the file content as a string
 */
function generateOutput(classes: SyncClassInfo[]): string {
  const sections: string[] = [GENERATED_FILE_HEADER]

  if (classes.length === 0) {
    sections.push('')
    sections.push(
      '// No ISync classes with @VerifySync fields found in src/ directory.',
    )
    return sections.join('\n')
  }

  sections.push('')
  sections.push('// -----------------------------------------------------------------------')
  sections.push('// Nested ISync helper — handles fields that are themselves ISync objects')
  sections.push('// The generated hash function for the nested type is looked up by class name')
  sections.push('// -----------------------------------------------------------------------')
  sections.push('')
  sections.push(`function hashNested(nested: ISync): number {`)
  sections.push(`  // Use the registered hash function for the nested type`)
  sections.push(`  // Falls back to 0 if no hash function is registered`)
  sections.push(`  const ctorName = nested.constructor?.name`)
  sections.push(`  if (!ctorName) return 0`)
  sections.push(`  // Try lookup by convention: registered functions follow naming pattern`)
  sections.push(`  const fn = (self as any).__syncHashFunctions?.get(ctorName)`)
  sections.push(`  return typeof fn === 'function' ? fn(nested) : 0`)
  sections.push(`}`)

  // Emit imports for classes that are used as field types
  const neededImports = new Set<string>()
  for (const cls of classes) {
    for (const field of cls.fields) {
      if (field.customHashType) {
        neededImports.add(field.customHashType)
      }
    }
  }

  sections.push('')
  sections.push('// -----------------------------------------------------------------------')
  sections.push('// Generated hash functions')
  sections.push('// -----------------------------------------------------------------------')

  for (const cls of classes) {
    sections.push('')
    sections.push(emitHashFunction(cls))
  }

  sections.push('')
  sections.push('// -----------------------------------------------------------------------')
  sections.push('// Self-registration (executes at import time)')
  sections.push('// -----------------------------------------------------------------------')
  sections.push('')

  for (const cls of classes) {
    const funcName = `computeSyncHash_${cls.className}`
    sections.push(
      `registerSyncHash('${cls.className}', ${funcName} as (obj: ISync) => number)`,
    )
  }

  sections.push('')

  return sections.join('\n')
}

// ---------------------------------------------------------------------------
// Directory Scanner
// ---------------------------------------------------------------------------

/**
 * Recursively find all .ts files in a directory, excluding test and generated files.
 */
function findTsFiles(dir: string): string[] {
  const files: string[] = []
  const entries = fs.readdirSync(dir, { withFileTypes: true })

  for (const entry of entries) {
    const fullPath = path.join(dir, entry.name)

    if (entry.name.startsWith('.') || entry.name === 'node_modules') {
      continue
    }

    if (entry.isDirectory()) {
      // Skip test directories
      if (entry.name === '__e2e__' || entry.name === '__tests__') {
        continue
      }
      files.push(...findTsFiles(fullPath))
    } else if (
      entry.isFile() &&
      entry.name.endsWith('.ts') &&
      !entry.name.endsWith('.test.ts') &&
      !entry.name.endsWith('.e2e.ts') &&
      !entry.name.includes('.generated.')
    ) {
      files.push(fullPath)
    }
  }

  return files
}

/**
 * Scan an entire directory tree for ISync classes.
 *
 * @param rootDir — the root directory to scan (e.g., path to src/)
 * @returns all discovered sync classes sorted by class name
 */
function scanDirectory(rootDir: string): SyncClassInfo[] {
  const files = findTsFiles(rootDir)
  const allClasses: SyncClassInfo[] = []

  for (const file of files) {
    try {
      const classes = scanSourceFile(file)
      allClasses.push(...classes)
    } catch (err) {
      console.warn(
        `sync-hash-generator: warning: could not scan "${file}":`,
        (err as Error).message,
      )
    }
  }

  // Sort by class name for deterministic output
  allClasses.sort((a, b) => a.className.localeCompare(b.className))
  return allClasses
}

// ---------------------------------------------------------------------------
// Vite Plugin
// ---------------------------------------------------------------------------

/**
 * Vite plugin that regenerates sync-hashes.generated.ts when source files change.
 *
 * This ensures the generated file is always up-to-date during development.
 * In production builds, the generated file should be committed to version control.
 */
export function syncHashVitePlugin(): {
  name: string
  buildStart: () => void
  configureServer: (server: {
    watcher: { on: (event: string, fn: (path: string) => void) => void }
  }) => void
} {
  const srcDir = path.resolve(process.cwd(), 'src')
  const outputPath = path.resolve(
    process.cwd(),
    'src/OpenRA.Game/sync-hashes.generated.ts',
  )

  function regenerate(): void {
    try {
      const classes = scanDirectory(srcDir)
      const output = generateOutput(classes)
      fs.writeFileSync(outputPath, output, 'utf-8')
      console.log(
        `[sync-hash-generator] Generated sync hashes for ${classes.length} ISync class(es)`,
      )
      if (classes.length > 0) {
        for (const cls of classes) {
          console.log(
            `  - ${cls.className}: ${cls.fields.length} field(s) [${cls.fields.map((f) => f.name).join(', ')}]`,
          )
        }
      }
    } catch (err) {
      console.error('[sync-hash-generator] Error:', (err as Error).message)
    }
  }

  return {
    name: 'sync-hash-generator',
    buildStart() {
      regenerate()
    },
    configureServer(server) {
      // Regenerate when source files change
      server.watcher.on('change', (filePath: string) => {
        if (
          filePath.startsWith(srcDir) &&
          filePath.endsWith('.ts') &&
          !filePath.includes('.generated.')
        ) {
          regenerate()
        }
      })
    },
  }
}

// ---------------------------------------------------------------------------
// CLI entry point
// ---------------------------------------------------------------------------

/**
 * Run the generator as a standalone script.
 *
 * Usage: npx tsx utils/sync-hash-generator.ts
 */
function main(): void {
  const cwd = process.cwd()
  const srcDir = path.resolve(cwd, 'src')
  const outputPath = path.resolve(
    cwd,
    'src/OpenRA.Game/sync-hashes.generated.ts',
  )

  console.log('[sync-hash-generator] Scanning source directory:', srcDir)

  const classes = scanDirectory(srcDir)

  if (classes.length === 0) {
    console.log(
      '[sync-hash-generator] No ISync classes with @VerifySync fields found.',
    )
  } else {
    console.log(
      `[sync-hash-generator] Found ${classes.length} ISync class(es):`,
    )
    for (const cls of classes) {
      console.log(
        `  - ${cls.className}: ${cls.fields.map((f) => f.name).join(', ')}`,
      )
    }
  }

  const output = generateOutput(classes)
  fs.mkdirSync(path.dirname(outputPath), { recursive: true })
  fs.writeFileSync(outputPath, output, 'utf-8')

  console.log(`[sync-hash-generator] Output written to: ${outputPath}`)
  console.log(`[sync-hash-generator] Generated ${output.split('\n').length} lines`)
}

// Run as CLI if this is the main module
const isMainModule =
  typeof process !== 'undefined' &&
  process.argv[1] &&
  (process.argv[1].endsWith('sync-hash-generator.ts') ||
    process.argv[1].endsWith('sync-hash-generator'))

if (isMainModule) {
  main()
}
