/**
 * camera-controls.spec.ts — Automated acceptance test for Chapter 7 Phase B Camera System
 * GENERATED BY: Kimi MCP (kimi_analyze)
 *
 * Test page: /test/ch07-input-camera/camera-controls/
 * Type: Babylon.js 3D WebGL Canvas scene (visual + programmatic verification)
 *
 * Acceptance criteria covered:
 *   E1. Coordinate-system orientation (5 checks)
 *   E2. Zoom-to-cursor precision and boundary clamping (3 checks)
 *   E3. Edge-scroll detection and pan boundary clamping (5 checks)
 *   E4. Orthographic / perspective mode switch (1 check)
 *
 * Implementation notes:
 *   - Babylon.js Vector3 objects are not serializable across page.evaluate(), so
 *     all harness wrappers below convert them to plain {x,y,z} objects before
 *     returning.
 *   - Harness pick/zoom helpers expect coordinates relative to the canvas client
 *     rect, while Playwright mouse actions use viewport coordinates.
 */
import { test, expect, type Page } from '@playwright/test';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const EVIDENCE_DIR = path.join(__dirname, 'evidence', 'camera-controls');

const TEST_URL = '/test/ch07-input-camera/camera-controls/';

// ------------------------------------------------------------------
// Harness type definitions (mirror the runtime __cameraTestHarness API)
// ------------------------------------------------------------------

interface WPos {
  x: number;
  y: number;
  z: number;
}

interface Vec3 {
  x: number;
  y: number;
  z: number;
}

interface ScreenPos {
  x: number;
  y: number;
}

interface MarkerPosition {
  label: string;
  wpos: WPos;
  vec3: Vec3;
  screenPos: ScreenPos;
}

interface CameraTestHarness {
  scene: unknown;
  camera: unknown;
  engine: unknown;
  getCurrentZoom: () => number;
  getCameraMode: () => 'ortho' | 'persp';
  getCameraTarget: () => Vec3;
  getLastWPosUnderCursor: () => WPos | null;
  getReferenceWPos: () => WPos | null;
  pickTerrainAt: (screenX: number, screenY: number) => Vec3 | null;
  wPosToVector3: (wx: number, wy: number, wz: number) => Vec3;
  vector3ToWPos: (v: Vec3) => WPos;
  setZoom: (factor: number) => void;
  zoomAtCursor: (factor: number, screenX: number, screenY: number) => void;
  setReferencePoint: (wx: number, wy: number, wz: number) => void;
  getMarkerPositions: () => MarkerPosition[];
}

interface CanvasRect {
  left: number;
  top: number;
  width: number;
  height: number;
  right: number;
  bottom: number;
  centerX: number;
  centerY: number;
}

// ------------------------------------------------------------------
// Helpers
// ------------------------------------------------------------------

function ensureEvidenceDir(): void {
  if (!fs.existsSync(EVIDENCE_DIR)) {
    fs.mkdirSync(EVIDENCE_DIR, { recursive: true });
  }
}

async function screenshot(page: Page, name: string): Promise<string> {
  ensureEvidenceDir();
  const p = path.join(EVIDENCE_DIR, `${name}.png`);
  await page.screenshot({ path: p, fullPage: false });
  return p;
}

async function waitForHarness(page: Page): Promise<void> {
  await page.waitForFunction(() => (window as any).__cameraTestHarness !== undefined, {
    timeout: 15000,
  });
}

async function waitForCanvas(page: Page): Promise<void> {
  await page.waitForSelector('#renderCanvas', { state: 'visible', timeout: 15000 });
}

/** Wait at least two render frames (~100 ms) so the WebGL scene is stable. */
async function waitForRenderFrames(page: Page, frames = 2): Promise<void> {
  // In headless mode the engine may be software-rendered; a small fixed delay
  // is acceptable and keeps tests deterministic.
  await page.waitForTimeout(frames * 50);
}

async function getCanvasRect(page: Page): Promise<CanvasRect> {
  const rect = await page.evaluate(() => {
    const canvas = document.getElementById('renderCanvas') as HTMLCanvasElement | null;
    if (!canvas) return null;
    const r = canvas.getBoundingClientRect();
    return {
      left: r.left,
      top: r.top,
      width: r.width,
      height: r.height,
      right: r.right,
      bottom: r.bottom,
      centerX: r.left + r.width / 2,
      centerY: r.top + r.height / 2,
    };
  });
  expect(rect, 'renderCanvas must be present and measurable').not.toBeNull();
  return rect as CanvasRect;
}

async function resetCamera(page: Page): Promise<void> {
  await page.click('#btn-reset-cam');
  await waitForRenderFrames(page);
}

async function resetZoom(page: Page): Promise<void> {
  await page.click('#btn-zoom-reset');
  await waitForRenderFrames(page);
}

async function ensureOrthoAndReset(page: Page): Promise<void> {
  const mode = await getCameraMode(page);
  if (mode === 'persp') {
    await page.click('#btn-toggle-mode');
    await waitForRenderFrames(page);
  }
  await resetZoom(page);
  await resetCamera(page);
}

// ------------------------------------------------------------------
// Harness wrappers — serialize Babylon Vector3 as plain {x,y,z} so the
// values survive the page.evaluate() boundary.
// ------------------------------------------------------------------

async function getCameraMode(page: Page): Promise<'ortho' | 'persp' | undefined> {
  return page.evaluate(() => {
    const h = (window as any).__cameraTestHarness as CameraTestHarness | undefined;
    return h?.getCameraMode();
  });
}

async function getCameraTargetPlain(page: Page): Promise<Vec3 | undefined> {
  return page.evaluate(() => {
    const h = (window as any).__cameraTestHarness as CameraTestHarness | undefined;
    const t = h?.getCameraTarget();
    return t ? { x: t.x, y: t.y, z: t.z } : undefined;
  });
}

async function pickTerrainAtPlain(page: Page, screenX: number, screenY: number): Promise<Vec3 | null> {
  return page.evaluate(({ x, y }) => {
    const h = (window as any).__cameraTestHarness as CameraTestHarness;
    const p = h.pickTerrainAt(x, y);
    return p ? { x: p.x, y: p.y, z: p.z } : null;
  }, { x: screenX, y: screenY });
}

async function setReferencePointFromVec3(page: Page, v: Vec3): Promise<void> {
  await page.evaluate(({ x, y, z }) => {
    const h = (window as any).__cameraTestHarness as CameraTestHarness;
    // Use Math.round for consistency with vec3ToWPosLocal
    h.setReferencePoint(Math.round(x * 1024), Math.round(z * 1024), Math.round(y * 512));
  }, { x: v.x, y: v.y, z: v.z });
}

async function getMarkerPositionsPlain(page: Page): Promise<MarkerPosition[]> {
  return page.evaluate(() => {
    const h = (window as any).__cameraTestHarness as CameraTestHarness | undefined;
    return (h?.getMarkerPositions() ?? []).map((m) => ({
      label: m.label,
      wpos: m.wpos,
      vec3: { x: m.vec3.x, y: m.vec3.y, z: m.vec3.z },
      screenPos: m.screenPos,
    }));
  });
}

async function getMarkerByLabel(page: Page, label: string): Promise<MarkerPosition | undefined> {
  const markers = await getMarkerPositionsPlain(page);
  return markers.find((m) => m.label === label);
}

async function zoomAtCursorPlain(page: Page, factor: number, screenX: number, screenY: number): Promise<void> {
  await page.evaluate(({ f, x, y }) => {
    const h = (window as any).__cameraTestHarness as CameraTestHarness;
    h.zoomAtCursor(f, x, y);
  }, { f: factor, x: screenX, y: screenY });
}

function wposDrift(a: WPos, b: WPos): number {
  return Math.max(Math.abs(a.x - b.x), Math.abs(a.y - b.y), Math.abs(a.z - b.z));
}

/** Convert a Babylon Vector3 to OpenRA WPos using the project scales. */
function vec3ToWPosLocal(v: Vec3): WPos {
  return {
    x: Math.round(v.x * 1024),
    y: Math.round(v.z * 1024),
    z: Math.round(v.y * 512),
  };
}

function vec3InMapBounds(v: Vec3): boolean {
  return v.x >= 0 && v.x <= 10 && v.z >= 0 && v.z <= 10;
}

// ------------------------------------------------------------------
// Test suite
// ------------------------------------------------------------------

test.describe('Camera Controls Acceptance Test (E1-E4)', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(TEST_URL);
    await waitForCanvas(page);
    await waitForHarness(page);
    await waitForRenderFrames(page, 3);
  });

  // ================================================================
  // E1. Coordinate-system orientation
  // ================================================================

  test('E1.1 - Red +X marker appears right of origin on screen', async ({ page }) => {
    const origin = await getMarkerByLabel(page, 'Origin');
    const xRight = await getMarkerByLabel(page, '+X_Right');
    expect(origin).toBeDefined();
    expect(xRight).toBeDefined();

    const diff = xRight!.screenPos.x - origin!.screenPos.x;
    expect(diff, `+X_Right x(${xRight!.screenPos.x}) should be > Origin x(${origin!.screenPos.x})`).toBeGreaterThan(20);

    await screenshot(page, 'e1-1-coordinate-system-overview');
  });

  test('E1.2 - Blue +Z marker appears above origin on screen (+Z away from camera, projects higher)', async ({ page }) => {
    const origin = await getMarkerByLabel(page, 'Origin');
    const zSouth = await getMarkerByLabel(page, '+Z_South');
    expect(origin).toBeDefined();
    expect(zSouth).toBeDefined();

    // +Z is further from camera (alpha=-PI/2, camera at -Z side), projects ABOVE origin on screen
    const diff = origin!.screenPos.y - zSouth!.screenPos.y;
    expect(diff, `+Z_South y(${zSouth!.screenPos.y}) should be < Origin y(${origin!.screenPos.y}) — +Z appears above`).toBeGreaterThan(20);

    await screenshot(page, 'e1-2-blue-z-above-origin');
  });

  test('E1.3 - Dark red -X marker appears left of origin on screen', async ({ page }) => {
    const origin = await getMarkerByLabel(page, 'Origin');
    const xLeft = await getMarkerByLabel(page, '-X_Left');
    expect(origin).toBeDefined();
    expect(xLeft).toBeDefined();

    expect(xLeft!.screenPos.x, `-X_Left x(${xLeft!.screenPos.x}) should be < Origin x(${origin!.screenPos.x})`).toBeLessThan(
      origin!.screenPos.x,
    );

    await screenshot(page, 'e1-3-dark-red-x-left-origin');
  });

  test('E1.4 - Dark blue -Z marker appears below origin on screen (-Z near camera, projects lower)', async ({ page }) => {
    const origin = await getMarkerByLabel(page, 'Origin');
    const zNorth = await getMarkerByLabel(page, '-Z_North');
    expect(origin).toBeDefined();
    expect(zNorth).toBeDefined();

    // -Z is closer to camera (alpha=-PI/2, camera at -Z side), projects BELOW origin on screen
    const diff = zNorth!.screenPos.y - origin!.screenPos.y;
    expect(diff, `-Z_North y(${zNorth!.screenPos.y}) should be > Origin y(${origin!.screenPos.y}) — -Z appears below`).toBeGreaterThan(20);

    await screenshot(page, 'e1-4-dark-blue-z-below-origin');
  });

  test('E1.5 - Green +Height marker has y=2.0 and vertical line to ground', async ({ page }) => {
    const hMarker = await getMarkerByLabel(page, '+Height');
    expect(hMarker).toBeDefined();
    expect(hMarker!.vec3.y).toBeCloseTo(2.0, 3);

    // The harness stores wpos with world Z in the y slot. A vertical drop line
    // exists when the marker's ground projection (wz = 0) is on the terrain.
    expect(hMarker!.wpos.z).toBeGreaterThan(0);

    await screenshot(page, 'e1-5-green-height-marker');
  });

  // ================================================================
  // E2. Zoom-to-cursor precision
  // ================================================================

  test('E2.1 - Zoom at crosshair keeps world position stable within ±2 su', async ({ page }) => {
    await ensureOrthoAndReset(page);
    const rect = await getCanvasRect(page);
    // Mouse coordinates are viewport-relative; harness pick/zoom helpers expect
    // coordinates relative to the canvas client rect.
    const cx = rect.centerX;
    const cy = rect.centerY;
    const cxc = rect.width / 2;
    const cyc = rect.height / 2;

    // Hover the crosshair so the harness knows the cursor location.
    await page.mouse.move(cx, cy);
    await waitForRenderFrames(page);

    const basePicked = await pickTerrainAtPlain(page, cxc, cyc);
    expect(basePicked, 'terrain must be pickable at crosshair').not.toBeNull();
    await setReferencePointFromVec3(page, basePicked!);

    const baseRef = await page.evaluate(() => {
      const h = (window as any).__cameraTestHarness as CameraTestHarness;
      return h.getReferenceWPos();
    });
    expect(baseRef, 'reference point must be set').not.toBeNull();

    // Requirement: step from 0.5x → 1.0x → 3.0x.
    const steps = [0.5, 1.0, 3.0];
    for (const targetZoom of steps) {
      await zoomAtCursorPlain(page, targetZoom, cxc, cyc);
      await waitForRenderFrames(page, 3);

      const picked = await pickTerrainAtPlain(page, cxc, cyc);
      const ref = await page.evaluate(() => {
        const h = (window as any).__cameraTestHarness as CameraTestHarness;
        return h.getReferenceWPos();
      });
      const zoom = await page.evaluate(() => {
        const h = (window as any).__cameraTestHarness as CameraTestHarness;
        return h.getCurrentZoom();
      });
      const target = await getCameraTargetPlain(page);

      expect(zoom).toBeCloseTo(targetZoom, 1);
      expect(picked, `terrain pickable after zoom to ${targetZoom}x`).not.toBeNull();
      expect(ref, `reference still locked after zoom to ${targetZoom}x`).not.toBeNull();
      expect(target, `camera target available after zoom to ${targetZoom}x`).not.toBeUndefined();

      const pickedWPos = vec3ToWPosLocal(picked!);
      const drift = wposDrift(pickedWPos, ref!);
      expect(drift, `drift at crosshair after ${targetZoom}x should be ≤ 2 su`).toBeLessThanOrEqual(2);
      expect(vec3InMapBounds(target!), `target inside map after ${targetZoom}x`).toBe(true);
    }

    await screenshot(page, 'e2-1-zoom-at-crosshair');
  });

  test('E2.2 - Zoom at arbitrary screen point keeps world position stable within ±3 su', async ({ page }) => {
    await ensureOrthoAndReset(page);
    const rect = await getCanvasRect(page);
    // Pick a non-center point (top-left quadrant, away from edges and UI).
    // Mouse uses viewport coordinates; harness helpers use canvas-relative.
    const px = Math.round(rect.left + rect.width * 0.35);
    const py = Math.round(rect.top + rect.height * 0.4);
    const pxc = rect.width * 0.35;
    const pyc = rect.height * 0.4;

    await page.mouse.move(px, py);
    await waitForRenderFrames(page);

    const basePicked = await pickTerrainAtPlain(page, pxc, pyc);
    expect(basePicked, 'terrain must be pickable at arbitrary point').not.toBeNull();
    await setReferencePointFromVec3(page, basePicked!);

    const baseRef = await page.evaluate(() => {
      const h = (window as any).__cameraTestHarness as CameraTestHarness;
      return h.getReferenceWPos();
    });
    expect(baseRef, 'reference point must be set').not.toBeNull();

    // Requirement: exercise min (0.5x) and max (3.0x) zoom plus an intermediate step.
    const steps = [0.5, 1.5, 3.0];
    for (const targetZoom of steps) {
      await zoomAtCursorPlain(page, targetZoom, pxc, pyc);
      await waitForRenderFrames(page, 3);

      const picked = await pickTerrainAtPlain(page, pxc, pyc);
      const ref = await page.evaluate(() => {
        const h = (window as any).__cameraTestHarness as CameraTestHarness;
        return h.getReferenceWPos();
      });
      const zoom = await page.evaluate(() => {
        const h = (window as any).__cameraTestHarness as CameraTestHarness;
        return h.getCurrentZoom();
      });
      const target = await getCameraTargetPlain(page);

      expect(zoom).toBeCloseTo(targetZoom, 1);
      expect(picked, `terrain pickable after zoom ${targetZoom}x`).not.toBeNull();
      expect(ref, `reference locked after zoom ${targetZoom}x`).not.toBeNull();
      expect(target, `camera target available after zoom ${targetZoom}x`).not.toBeUndefined();

      const pickedWPos = vec3ToWPosLocal(picked!);
      const drift = wposDrift(pickedWPos, ref!);
      expect(drift, `drift at arbitrary point after ${targetZoom}x should be ≤ 3 su`).toBeLessThanOrEqual(3);
      expect(vec3InMapBounds(target!), `target inside map after ${targetZoom}x`).toBe(true);
    }

    await screenshot(page, 'e2-2-zoom-at-arbitrary-point');
  });

  test('E2.3 - Zoom operations keep camera target within [0,10]×[0,10] map bounds', async ({ page }) => {
    await ensureOrthoAndReset(page);
    const rect = await getCanvasRect(page);
    const points = [
      { label: 'center', mx: rect.centerX, my: rect.centerY, hx: rect.width / 2, hy: rect.height / 2 },
      { label: 'near-top-left', mx: rect.left + 80, my: rect.top + 80, hx: 80, hy: 80 },
      { label: 'near-bottom-right', mx: rect.right - 80, my: rect.bottom - 80, hx: rect.width - 80, hy: rect.height - 80 },
    ];

    for (const pt of points) {
      await page.mouse.move(pt.mx, pt.my);
      await waitForRenderFrames(page);

      for (const factor of [0.5, 1.0, 2.0, 3.0]) {
        await page.evaluate(({ f, x, y }) => {
          const h = (window as any).__cameraTestHarness as CameraTestHarness;
          h.zoomAtCursor(f, x, y);
        }, { f: factor, x: pt.hx, y: pt.hy });
        await waitForRenderFrames(page, 2);

        const target = await getCameraTargetPlain(page);

        expect(target, `target must exist for ${pt.label} @ ${factor}x`).not.toBeNull();
        expect(
          vec3InMapBounds(target!),
          `target (${target!.x.toFixed(3)}, ${target!.z.toFixed(3)}) must be inside [0,10]×[0,10] for ${pt.label} @ ${factor}x`,
        ).toBe(true);
      }
    }

    await screenshot(page, 'e2-3-zoom-boundary-clamp');
  });

  // ================================================================
  // E3. Edge-scroll detection and pan boundary clamping
  // ================================================================

  test('E3.1 - Top edge zone activates when cursor ≤15 px from top', async ({ page }) => {
    await resetCamera(page);
    const rect = await getCanvasRect(page);

    await page.mouse.move(rect.centerX, rect.top + 12);
    await waitForRenderFrames(page);
    const activeInside = await page.evaluate(() => document.getElementById('edge-top')?.classList.contains('active'));
    expect(activeInside, 'top edge should be active at 12 px').toBe(true);

    await page.mouse.move(rect.centerX, rect.top + 18);
    await waitForRenderFrames(page);
    const activeOutside = await page.evaluate(() => document.getElementById('edge-top')?.classList.contains('active'));
    expect(activeOutside, 'top edge should be inactive at 18 px').toBe(false);

    await screenshot(page, 'e3-1-top-edge-zone');
  });

  test('E3.2 - Bottom edge zone activates when cursor ≤15 px from bottom', async ({ page }) => {
    await resetCamera(page);
    const rect = await getCanvasRect(page);

    // Use 12px/18px (not 15px/17px) for robustness against floating-point
    // rounding when getBoundingClientRect().bottom has fractional values.
    // The edge scroll margin is 15px; 12px is well inside, 18px is well outside.
    await page.mouse.move(rect.centerX, rect.bottom - 12);
    await waitForRenderFrames(page);
    const activeInside = await page.evaluate(() => document.getElementById('edge-bottom')?.classList.contains('active'));
    expect(activeInside, 'bottom edge should be active at 12 px').toBe(true);

    await page.mouse.move(rect.centerX, rect.bottom - 18);
    await waitForRenderFrames(page);
    const activeOutside = await page.evaluate(() => document.getElementById('edge-bottom')?.classList.contains('active'));
    expect(activeOutside, 'bottom edge should be inactive at 18 px').toBe(false);

    await screenshot(page, 'e3-2-bottom-edge-zone');
  });

  test('E3.3 - Left edge zone activates when cursor ≤15 px from left', async ({ page }) => {
    await resetCamera(page);
    const rect = await getCanvasRect(page);

    await page.mouse.move(rect.left + 12, rect.centerY);
    await waitForRenderFrames(page);
    const activeInside = await page.evaluate(() => document.getElementById('edge-left')?.classList.contains('active'));
    expect(activeInside, 'left edge should be active at 12 px').toBe(true);

    await page.mouse.move(rect.left + 18, rect.centerY);
    await waitForRenderFrames(page);
    const activeOutside = await page.evaluate(() => document.getElementById('edge-left')?.classList.contains('active'));
    expect(activeOutside, 'left edge should be inactive at 18 px').toBe(false);

    await screenshot(page, 'e3-3-left-edge-zone');
  });

  test('E3.4 - Right edge zone activates when cursor ≤15 px from right', async ({ page }) => {
    await resetCamera(page);
    const rect = await getCanvasRect(page);

    await page.mouse.move(rect.right - 12, rect.centerY);
    await waitForRenderFrames(page);
    const activeInside = await page.evaluate(() => document.getElementById('edge-right')?.classList.contains('active'));
    expect(activeInside, 'right edge should be active at 12 px').toBe(true);

    await page.mouse.move(rect.right - 18, rect.centerY);
    await waitForRenderFrames(page);
    const activeOutside = await page.evaluate(() => document.getElementById('edge-right')?.classList.contains('active'));
    expect(activeOutside, 'right edge should be inactive at 18 px').toBe(false);

    await screenshot(page, 'e3-4-right-edge-zone');
  });

  test('E3.5 - Pan drag keeps camera target inside [0,10]×[0,10]', async ({ page }) => {
    await ensureOrthoAndReset(page);
    const rect = await getCanvasRect(page);

    // Start dragging from center and pull toward each edge in turn.
    const dragTargets = [
      { x: rect.left + 20, y: rect.centerY, name: 'left' },
      { x: rect.right - 20, y: rect.centerY, name: 'right' },
      { x: rect.centerX, y: rect.top + 20, name: 'top' },
      { x: rect.centerX, y: rect.bottom - 20, name: 'bottom' },
    ];

    for (const target of dragTargets) {
      await page.mouse.move(rect.centerX, rect.centerY);
      // Pan is bound to Shift + left-click-drag in this test page.
      await page.keyboard.down('Shift');
      await page.mouse.down();

      const steps = 6;
      for (let i = 1; i <= steps; i++) {
        const tx = rect.centerX + ((target.x - rect.centerX) * i) / steps;
        const ty = rect.centerY + ((target.y - rect.centerY) * i) / steps;
        await page.mouse.move(tx, ty);
        await waitForRenderFrames(page, 1);

        const t = await getCameraTargetPlain(page);
        expect(t, `target must exist while dragging toward ${target.name}`).not.toBeNull();
        expect(
          vec3InMapBounds(t!),
          `target (${t!.x.toFixed(3)}, ${t!.z.toFixed(3)}) must stay inside map while dragging toward ${target.name}`,
        ).toBe(true);
      }

      await page.mouse.up();
      await page.keyboard.up('Shift');
      await resetCamera(page);
    }

    await screenshot(page, 'e3-5-pan-boundary-clamp');
  });

  // ================================================================
  // E4. Camera mode switch
  // ================================================================

  test('E4.1 - Orthographic to perspective switch shifts marker positions ≤350 px', async ({ page }) => {
    await ensureOrthoAndReset(page);
    await waitForRenderFrames(page, 3);

    const beforeMode = await getCameraMode(page);
    expect(beforeMode).toBe('ortho');

    // Exclude corner markers (MapCorner_*) — they are at the view periphery
    // where perspective foreshortening inherently causes larger shifts.
    // Only check primary markers near the view center.
    const allBefore = await getMarkerPositionsPlain(page);
    const beforeMarkers = allBefore
      .filter((m) => !m.label.startsWith('MapCorner_'))
      .map((m) => ({ label: m.label, x: m.screenPos.x, y: m.screenPos.y }));
    expect(beforeMarkers.length).toBeGreaterThan(0);

    await screenshot(page, 'e4-1-ortho-mode');

    await page.click('#btn-toggle-mode');
    await waitForRenderFrames(page, 4);

    const afterMode = await getCameraMode(page);
    expect(afterMode).toBe('persp');

    const allAfter = await getMarkerPositionsPlain(page);
    const afterMarkers = allAfter
      .filter((m) => !m.label.startsWith('MapCorner_'))
      .map((m) => ({ label: m.label, x: m.screenPos.x, y: m.screenPos.y }));

    await screenshot(page, 'e4-1-persp-mode');

    for (const b of beforeMarkers) {
      const a = afterMarkers.find((m) => m.label === b.label);
      expect(a, `marker ${b.label} still tracked after mode switch`).toBeDefined();
      const dx = Math.abs(a!.x - b.x);
      const dy = Math.abs(a!.y - b.y);
      expect(dx, `marker ${b.label} x-shift ${dx}px should be ≤ 350 px`).toBeLessThanOrEqual(350);
      expect(dy, `marker ${b.label} y-shift ${dy}px should be ≤ 350 px`).toBeLessThanOrEqual(350);
    }

    // Return to ortho to keep subsequent tests deterministic if they are ever chained.
    await page.click('#btn-toggle-mode');
    await waitForRenderFrames(page, 3);
  });
});
