/**
 * Playwright E2E tests for ch08-weapons-combat/railgun-trail
 *
 * Verifies R1-R6: instant impact, color matching, helix visibility,
 * trail fade, impact accuracy, and projectile disposal.
 *
 * IMPORTANT: In headless mode, the Babylon.js render loop runs at uncontrolled
 * frame rate (much faster than 60fps). Since the sim is frame-driven (2 frames
 * per tick), ticks advance very quickly. To get reliable state checks:
 *  - For immediate post-fire checks (R3, R4.1): run fire + check in a single
 *    synchronous page.evaluate to avoid interleaving with the render loop.
 *  - For tick-dependent checks (R4.2, R6.1): use page.waitForFunction to poll
 *    the Railgun object's internal ticks counter.
 *
 * Generated by: acceptance-test-runner (STEP 2, revised)
 */
import { test, expect } from '@playwright/test';
import type { Page } from '@playwright/test';

const PAGE_URL = 'http://localhost:5173/test/ch08-weapons-combat/railgun-trail/';

// Evidence output path
const EVIDENCE_DIR = 'test-results/manual/ch08-weapons-combat/railgun-trail/evidence';

// Helper: wait for the harness to be ready
async function waitForHarness(page: Page, timeout = 10000) {
  await page.waitForFunction(
    () => typeof (window as any).__testHarness !== 'undefined',
    {},
    { timeout }
  );
}

// Helper: read impact position from diagnostic panel
async function getImpactPosition(page: Page): Promise<{ x: number; y: number; z: number } | null> {
  const text = await page.textContent('#diag-impactPos');
  if (!text || text === '-' || text.trim() === '') return null;
  const match = text.match(/\((\d+),\s*(\d+),\s*(\d+)\)/);
  if (!match) return null;
  return {
    x: parseInt(match[1]!, 10),
    y: parseInt(match[2]!, 10),
    z: parseInt(match[3]!, 10),
  };
}

// =============================================================================
// R1: Instant Impact
// =============================================================================
test.describe('R1 — Instant Impact (≤1 Tick)', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(PAGE_URL);
    await page.waitForSelector('canvas#renderCanvas', { timeout: 15000 });
    await waitForHarness(page);
    await page.waitForTimeout(500);
  });

  test('R1.1 — Impact count ≥ 1 after fire (impact on tick 0)', async ({ page }) => {
    // Fire + wait for at least one tick cycle
    await page.click('#btn-fire');
    // Poll: wait until a tick has actually run and impact detected
    await page.waitForFunction(
      () => (window as any).__testHarness.getImpacts() >= 1,
      {},
      { timeout: 10000 }
    );

    const impacts = await page.evaluate(() => (window as any).__testHarness.getImpacts());
    expect(impacts).toBeGreaterThanOrEqual(1);
  });

  test('R1.2 — Impact position at default target (10240, 5120, 0)', async ({ page }) => {
    await page.click('#btn-fire');
    await page.waitForFunction(
      () => (window as any).__testHarness.isImpacted(),
      {},
      { timeout: 5000 }
    );
    await page.waitForTimeout(100);

    const pos = await getImpactPosition(page);
    expect(pos).not.toBeNull();
    if (pos) {
      expect(Math.abs(pos.x - 10240)).toBeLessThanOrEqual(200);
      expect(Math.abs(pos.y - 5120)).toBeLessThanOrEqual(10);
    }
  });

  test('R1.3 — isImpacted() === true after fire', async ({ page }) => {
    await page.click('#btn-fire');
    await page.waitForFunction(
      () => (window as any).__testHarness.isImpacted(),
      {},
      { timeout: 5000 }
    );

    const impacted = await page.evaluate(() => (window as any).__testHarness.isImpacted());
    expect(impacted).toBe(true);

    const diagText = await page.textContent('#diag-impacted');
    expect(diagText?.trim().toUpperCase()).toBe('YES');
  });

  test('R1 — Screenshot: scene after fire (early capture)', async ({ page }) => {
    // Use synchronous fire+delay to catch scene before full fade
    await page.evaluate(() => {
      (window as any).__testHarness.fireRailgun();
    });
    // Very short wait to allow just 1-2 frames
    await page.waitForTimeout(30);
    await page.screenshot({ path: `${EVIDENCE_DIR}/screenshot-1-fire-impact.png` });
  });
});

// =============================================================================
// R2: Trail Color Matching
// =============================================================================
test.describe('R2 — Trail Color Matching', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(PAGE_URL);
    await page.waitForSelector('canvas#renderCanvas', { timeout: 15000 });
    await waitForHarness(page);
    await page.waitForTimeout(500);
  });

  test('R2.1 — Default beam color is Cyan [128, 255, 255]', async ({ page }) => {
    // Fire and check color synchronously (before sim advances)
    const color = await page.evaluate(() => {
      const h = (window as any).__testHarness;
      h.fireRailgun();
      return h.getTrailColor();
    });
    const beam = color.beam as number[];
    expect(beam[0]).toBeGreaterThanOrEqual(116);
    expect(beam[0]).toBeLessThanOrEqual(140);
    expect(beam[1]).toBeGreaterThanOrEqual(243);
    expect(beam[1]).toBeLessThanOrEqual(255);
    expect(beam[2]).toBeGreaterThanOrEqual(243);
    expect(beam[2]).toBeLessThanOrEqual(255);
  });

  test('R2.2 — Default helix color is Cyan [128, 255, 255]', async ({ page }) => {
    const color = await page.evaluate(() => {
      const h = (window as any).__testHarness;
      h.fireRailgun();
      return h.getTrailColor();
    });
    const helix = color.helix as number[];
    expect(helix[0]).toBeGreaterThanOrEqual(116);
    expect(helix[0]).toBeLessThanOrEqual(140);
    expect(helix[1]).toBeGreaterThanOrEqual(243);
    expect(helix[1]).toBeLessThanOrEqual(255);
    expect(helix[2]).toBeGreaterThanOrEqual(243);
    expect(helix[2]).toBeLessThanOrEqual(255);
  });

  test('R2.3 — Beam color changes to Red [255, 128, 128] after dropdown switch', async ({ page }) => {
    await page.selectOption('#config-beamColor', '255,128,128');
    await page.evaluate(() => (window as any).__testHarness.reset());
    await page.waitForTimeout(200);

    const color = await page.evaluate(() => {
      const h = (window as any).__testHarness;
      h.fireRailgun();
      return h.getTrailColor();
    });
    const beam = color.beam as number[];
    expect(beam[0]).toBeGreaterThanOrEqual(243);
    expect(beam[0]).toBeLessThanOrEqual(255);
    expect(beam[1]).toBeGreaterThanOrEqual(116);
    expect(beam[1]).toBeLessThanOrEqual(140);
    expect(beam[2]).toBeGreaterThanOrEqual(116);
    expect(beam[2]).toBeLessThanOrEqual(140);
  });

  test('R2 — Screenshot: Red beam + Orange helix', async ({ page }) => {
    await page.selectOption('#config-beamColor', '255,128,128');
    await page.selectOption('#config-helixColor', '255,200,128');
    await page.evaluate(() => (window as any).__testHarness.reset());
    await page.waitForTimeout(200);
    await page.evaluate(() => {
      (window as any).__testHarness.fireRailgun();
    });
    await page.waitForTimeout(50);
    await page.screenshot({ path: `${EVIDENCE_DIR}/screenshot-2-red-beam-orange-helix.png` });
  });
});

// =============================================================================
// R3: Helix Trail Visibility
// =============================================================================
test.describe('R3 — Helix Trail Visibility', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(PAGE_URL);
    await page.waitForSelector('canvas#renderCanvas', { timeout: 15000 });
    await waitForHarness(page);
    await page.waitForTimeout(500);
  });

  test('R3.1 — Helix LinesMesh exists immediately after fire', async ({ page }) => {
    // Fire + check scene in a SINGLE synchronous evaluate to avoid
    // the render loop advancing ticks before we can check.
    const result = await page.evaluate(() => {
      const h = (window as any).__testHarness;
      h.fireRailgun();
      const scene = h.scene;
      const helix = scene.getMeshByName('helix');
      return {
        helixExists: !!helix,
        helixEnabled: helix ? helix.isEnabled() : false,
      };
    });
    expect(result.helixExists).toBe(true);
    expect(result.helixEnabled).toBe(true);
  });

  test('R3.4 — Core beam LinesMesh exists immediately after fire', async ({ page }) => {
    const result = await page.evaluate(() => {
      const h = (window as any).__testHarness;
      h.fireRailgun();
      const scene = h.scene;
      const coreBeam = scene.getMeshByName('coreBeam');
      return {
        coreExists: !!coreBeam,
        coreEnabled: coreBeam ? coreBeam.isEnabled() : false,
      };
    });
    expect(result.coreExists).toBe(true);
    expect(result.coreEnabled).toBe(true);
  });

  test('R3 — Screenshot: Helix trail visible', async ({ page }) => {
    await page.evaluate(() => {
      (window as any).__testHarness.fireRailgun();
    });
    // Minimal wait for first frame render
    await page.waitForTimeout(16);
    await page.screenshot({ path: `${EVIDENCE_DIR}/screenshot-3-helix-trail.png` });
  });
});

// =============================================================================
// R4: Trail Fade Within ~5 Ticks
// =============================================================================
test.describe('R4 — Trail Fade (~5 Ticks)', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(PAGE_URL);
    await page.waitForSelector('canvas#renderCanvas', { timeout: 15000 });
    await waitForHarness(page);
    await page.waitForTimeout(500);
  });

  test('R4.1 — Tick 0: Railgun.beamAlpha = 255, helixAlpha = 255', async ({ page }) => {
    // Check the Railgun object's getter synchronously (ticks=0 at creation)
    const result = await page.evaluate(() => {
      const h = (window as any).__testHarness;
      h.fireRailgun();
      const rg = h.getActiveRailgun();
      return {
        beamAlpha: rg ? rg.beamAlpha : -1,
        helixAlpha: rg ? rg.helixAlpha : -1,
        ticks: rg ? rg.ticks : -1,
      };
    });
    expect(result.ticks).toBe(0);
    expect(result.beamAlpha).toBe(255);
    expect(result.helixAlpha).toBe(255);
  });

  test('R4.2 — Tick 3: beamAlpha ≈ 102 (255 - 51×3)', async ({ page }) => {
    await page.click('#btn-fire');
    // Wait until the Railgun's internal ticks >= 3
    await page.waitForFunction(
      () => {
        const rg = (window as any).__testHarness.getActiveRailgun();
        return rg && rg.ticks >= 3;
      },
      {},
      { timeout: 10000 }
    );

    const beamAlpha = await page.evaluate(() => {
      const rg = (window as any).__testHarness.getActiveRailgun();
      return rg ? rg.beamAlpha : -1;
    });
    // Allow ±15 tolerance for off-by-one tick
    expect(beamAlpha).toBeGreaterThanOrEqual(87);
    expect(beamAlpha).toBeLessThanOrEqual(117);
  });

  test('R4.3 — Tick 5: beamAlpha ≤ 5 (essentially zero)', async ({ page }) => {
    await page.click('#btn-fire');
    await page.waitForFunction(
      () => {
        const rg = (window as any).__testHarness.getActiveRailgun();
        return rg && rg.ticks >= 5;
      },
      {},
      { timeout: 10000 }
    );

    const beamAlpha = await page.evaluate(() => {
      const rg = (window as any).__testHarness.getActiveRailgun();
      return rg ? rg.beamAlpha : -1;
    });
    expect(beamAlpha).toBeLessThanOrEqual(5);
  });

  test('R4.4 — After fade, helix and coreBeam are disabled', async ({ page }) => {
    await page.click('#btn-fire');
    // Wait for beamAlpha to reach 0 (ticks >= 5)
    await page.waitForFunction(
      () => {
        const rg = (window as any).__testHarness.getActiveRailgun();
        return rg && rg.beamAlpha <= 0 && rg.helixAlpha <= 0;
      },
      {},
      { timeout: 10000 }
    );
    await page.waitForTimeout(100);

    const bothDisabled = await page.evaluate(() => {
      const scene = (window as any).__testHarness.scene;
      const helix = scene.getMeshByName('helix');
      const coreBeam = scene.getMeshByName('coreBeam');
      const helixOff = !helix || !helix.isEnabled();
      const coreOff = !coreBeam || !coreBeam.isEnabled();
      return helixOff && coreOff;
    });
    expect(bothDisabled).toBe(true);
  });

  test('R4 — Screenshot: after fade complete', async ({ page }) => {
    await page.click('#btn-fire');
    await page.waitForFunction(
      () => {
        const rg = (window as any).__testHarness.getActiveRailgun();
        return rg && rg.beamAlpha <= 0 && rg.helixAlpha <= 0;
      },
      {},
      { timeout: 10000 }
    );
    await page.waitForTimeout(100);
    await page.screenshot({ path: `${EVIDENCE_DIR}/screenshot-4-fade-complete.png` });
  });
});

// =============================================================================
// R5: Impact Position Accuracy
// =============================================================================
test.describe('R5 — Impact Position Accuracy', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(PAGE_URL);
    await page.waitForSelector('canvas#renderCanvas', { timeout: 15000 });
    await waitForHarness(page);
    await page.waitForTimeout(500);
  });

  test('R5.1 — |impactX - 10240| ≤ 100 su', async ({ page }) => {
    await page.click('#btn-fire');
    await page.waitForFunction(
      () => (window as any).__testHarness.isImpacted(),
      {},
      { timeout: 5000 }
    );

    const pos = await getImpactPosition(page);
    expect(pos).not.toBeNull();
    if (pos) {
      expect(Math.abs(pos.x - 10240)).toBeLessThanOrEqual(100);
    }
  });

  test('R5.2 — |impactY - 5120| ≤ 10 su', async ({ page }) => {
    await page.click('#btn-fire');
    await page.waitForFunction(
      () => (window as any).__testHarness.isImpacted(),
      {},
      { timeout: 5000 }
    );

    const pos = await getImpactPosition(page);
    expect(pos).not.toBeNull();
    if (pos) {
      expect(Math.abs(pos.y - 5120)).toBeLessThanOrEqual(10);
    }
  });
});

// =============================================================================
// R6: Projectile Disposal After Duration
// =============================================================================
test.describe('R6 — Projectile Disposal (Tick 16)', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(PAGE_URL);
    await page.waitForSelector('canvas#renderCanvas', { timeout: 15000 });
    await waitForHarness(page);
    await page.waitForTimeout(500);
  });

  test('R6.1 — Tick 16: isDestroyed === true', async ({ page }) => {
    await page.click('#btn-fire');
    // Wait for the Railgun to be destroyed (ticks > duration=15)
    await page.waitForFunction(
      () => {
        const rg = (window as any).__testHarness.getActiveRailgun();
        // null = already cleaned up, or isDestroyed = true
        return rg === null || rg.isDestroyed === true;
      },
      {},
      { timeout: 15000 }
    );

    const destroyed = await page.evaluate(() => {
      const rg = (window as any).__testHarness.getActiveRailgun();
      return rg ? rg.isDestroyed : true;
    });
    expect(destroyed).toBe(true);
  });

  test('R6.2 — After disposal, all visuals cleaned up', async ({ page }) => {
    await page.click('#btn-fire');
    await page.waitForFunction(
      () => {
        const rg = (window as any).__testHarness.getActiveRailgun();
        return rg === null || rg.isDestroyed === true;
      },
      {},
      { timeout: 15000 }
    );
    await page.waitForTimeout(200);

    const allClean = await page.evaluate(() => {
      const scene = (window as any).__testHarness.scene;
      const helix = scene.getMeshByName('helix');
      const coreBeam = scene.getMeshByName('coreBeam');
      const impact = scene.getMeshByName('impact');
      const helixOk = !helix || !helix.isEnabled();
      const coreOk = !coreBeam || !coreBeam.isEnabled();
      const impactOk = !impact || !impact.isEnabled();
      return helixOk && coreOk && impactOk;
    });
    expect(allClean).toBe(true);
  });
});

// =============================================================================
// Edge Cases
// =============================================================================
test.describe('Edge Cases', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto(PAGE_URL);
    await page.waitForSelector('canvas#renderCanvas', { timeout: 15000 });
    await waitForHarness(page);
    await page.waitForTimeout(500);
  });

  test('Rapid consecutive fire — no leftover visuals', async ({ page }) => {
    // Fire three times quickly
    for (let i = 0; i < 3; i++) {
      await page.evaluate(() => (window as any).__testHarness.fireRailgun());
      await page.waitForTimeout(200);
    }

    // Only the last fire's visuals should remain (1 helix at most)
    const meshCount = await page.evaluate(() => {
      const scene = (window as any).__testHarness.scene;
      let count = 0;
      const meshes = scene.meshes;
      for (let i = 0; i < meshes.length; i++) {
        if (meshes[i].name === 'helix' && meshes[i].isEnabled()) count++;
      }
      return count;
    });
    expect(meshCount).toBeLessThanOrEqual(1);
  });

  test('Color mismatch — Beam Red + Helix Orange fire independently colored', async ({ page }) => {
    await page.selectOption('#config-beamColor', '255,128,128');
    // Use Orange (255,200,128) - Green is not in the dropdown options
    await page.selectOption('#config-helixColor', '255,200,128');
    await page.evaluate(() => (window as any).__testHarness.reset());
    await page.waitForTimeout(200);

    const color = await page.evaluate(() => {
      const h = (window as any).__testHarness;
      h.fireRailgun();
      return h.getTrailColor();
    });
    const beam = color.beam as number[];
    const helix = color.helix as number[];

    // Beam should be red (high R, low G)
    expect(beam[0]).toBeGreaterThanOrEqual(240);
    expect(beam[1]).toBeLessThanOrEqual(140);

    // Helix should be orange (high R, high G)
    expect(helix[0]).toBeGreaterThanOrEqual(240);
    expect(helix[1]).toBeGreaterThanOrEqual(185);

    await page.evaluate(() => (window as any).__testHarness.fireRailgun());
    await page.waitForTimeout(50);
    await page.screenshot({ path: `${EVIDENCE_DIR}/screenshot-5-red-beam-orange-helix.png` });
  });
});
