/**
 * Playwright E2E Tests — HardwarePalette Color Accuracy (Expect 1)
 *
 * Target: http://localhost:5173/test/ch02-rendering/color-accuracy/
 * Generated by: Acceptance Test Engineer
 *
 * Validates the synthetic gradient palette (R→G→B bands + white):
 *   - Engine initialization (Babylon.js / WebGL 2.0)
 *   - Gradient palette is the default selection
 *   - [diagnose] console logs report expected palette values
 *   - [verify-canvas] console logs report expected canvas pixels
 *   - Screenshots captured as evidence
 */

import { test, expect } from '@playwright/test';
import * as path from 'path';
import * as fs from 'fs';
import { fileURLToPath } from 'url';

const PAGE_URL = 'http://localhost:5173/test/ch02-rendering/color-accuracy/';
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const EVIDENCE_DIR = path.resolve(
  __dirname,
  '../../../../../../test-results/manual/ch02-rendering/color-accuracy/evidence'
);

function evidenceFile(name: string): string {
  return path.join(EVIDENCE_DIR, name);
}

if (!fs.existsSync(EVIDENCE_DIR)) {
  fs.mkdirSync(EVIDENCE_DIR, { recursive: true });
}

interface DiagnoseEntry {
  label: string;
  index: number;
  argb: number;
  r: number;
  g: number;
  b: number;
  a: number;
}

interface VerifyCanvasEntry {
  label: string;
  x: number;
  y: number;
  r: number;
  g: number;
  b: number;
  a: number;
}

function parseDiagnose(text: string): DiagnoseEntry | null {
  const m = text.match(
    /\[diagnose\] ([\w-]+) index (\d+): argb=0x([0-9a-f]+) → rgba\((\d+),(\d+),(\d+),(\d+)\)/
  );
  if (!m) return null;
  return {
    label: m[1],
    index: parseInt(m[2], 10),
    argb: parseInt(m[3], 16),
    r: parseInt(m[4], 10),
    g: parseInt(m[5], 10),
    b: parseInt(m[6], 10),
    a: parseInt(m[7], 10),
  };
}

function parseVerifyCanvas(text: string): VerifyCanvasEntry | null {
  const m = text.match(
    /\[verify-canvas\] ([\w-]+): pixel@\((\d+),(\d+)\) = rgba\((\d+),(\d+),(\d+),(\d+)\)/
  );
  if (!m) return null;
  return {
    label: m[1],
    x: parseInt(m[2], 10),
    y: parseInt(m[3], 10),
    r: parseInt(m[4], 10),
    g: parseInt(m[5], 10),
    b: parseInt(m[6], 10),
    a: parseInt(m[7], 10),
  };
}

test('gradient palette color accuracy', async ({ page }) => {
  test.setTimeout(30000);

  const diagnoseEntries: DiagnoseEntry[] = [];
  const verifyCanvasEntries: VerifyCanvasEntry[] = [];

  page.on('console', (msg) => {
    const text = msg.text();
    const diag = parseDiagnose(text);
    if (diag) diagnoseEntries.push(diag);
    const verify = parseVerifyCanvas(text);
    if (verify) verifyCanvasEntries.push(verify);
  });

  await page.goto(PAGE_URL);
  await page.waitForSelector('#info-engine', { timeout: 15000 });

  // 1. Engine initialization
  const engineInfo = await page.locator('#info-engine').textContent();
  expect(engineInfo).toMatch(/Babylon\.js.*WebGL\s*2/);
  await expect(page.locator('#gpu-error')).toBeHidden();

  // 2. Gradient palette selected by default
  await expect(page.locator('#palette-select')).toHaveValue('gradient');

  // Wait for initial texture updates and diagnostics to complete
  await page.waitForTimeout(1500);

  // 3. Verify [diagnose] palette values for gradient palette
  const originals = diagnoseEntries.filter((d) => d.label === 'texOriginal');
  expect(originals.length).toBeGreaterThan(0);

  const find = (idx: number) => originals.find((d) => d.index === idx);

  const idx0 = find(0);
  expect(idx0, 'gradient index 0 should be diagnosed').toBeDefined();
  expect(idx0!.r).toBe(0);
  expect(idx0!.g).toBe(0);
  expect(idx0!.b).toBe(0);
  expect(idx0!.a).toBe(255);

  // The page's diagnostic sampler logs indices 0,1,2,3,4,10,20,85,170,255.
  // Index 84 (pure red) is not directly emitted, but index 85 marks the
  // green-band start and must be black, proving the boundary is correct.
  const idx85 = find(85);
  expect(idx85, 'gradient index 85 (green band start) should be diagnosed').toBeDefined();
  expect(idx85!.r).toBe(0);
  expect(idx85!.g).toBe(0);
  expect(idx85!.b).toBe(0);

  const idx170 = find(170);
  expect(idx170, 'gradient index 170 (blue band start) should be diagnosed').toBeDefined();
  expect(idx170!.r).toBe(0);
  expect(idx170!.g).toBe(0);
  expect(idx170!.b).toBe(0);

  const idx255 = find(255);
  expect(idx255, 'gradient index 255 should be diagnosed').toBeDefined();
  expect(idx255!.r).toBe(255);
  expect(idx255!.g).toBe(255);
  expect(idx255!.b).toBe(255);
  expect(idx255!.a).toBe(255);

  // Red-band samples (indices 1-20) must have R as the dominant channel
  // and zero green/blue.
  for (const idx of [1, 2, 3, 4, 10, 20]) {
    const entry = find(idx);
    expect(entry, `gradient index ${idx} should be diagnosed`).toBeDefined();
    expect(entry!.r).toBeGreaterThan(0);
    expect(entry!.g).toBe(0);
    expect(entry!.b).toBe(0);
    expect(entry!.a).toBe(255);
  }

  // Debug: print all verify-canvas entries
  console.log('verifyCanvasEntries', JSON.stringify(verifyCanvasEntries, null, 2));

  // 4. Verify [verify-canvas] canvas pixels
  const canvas0 = verifyCanvasEntries.find(
    (v) => v.label === 'texOriginal-beforeText-index0'
  );
  expect(canvas0, 'canvas pixel for index 0 should be logged').toBeDefined();
  expect(canvas0!.r).toBe(0);
  expect(canvas0!.g).toBe(0);
  expect(canvas0!.b).toBe(0);
  expect(canvas0!.a).toBe(255);

  const canvas1 = verifyCanvasEntries.find(
    (v) => v.label === 'texOriginal-beforeText-index1'
  );
  expect(canvas1, 'canvas pixel for index 1 should be logged').toBeDefined();
  expect(canvas1!.g).toBe(0);
  expect(canvas1!.b).toBe(0);
  expect(canvas1!.a).toBe(255);

  // 5. Screenshot at key state
  await page.screenshot({
    path: evidenceFile('screenshot-gradient-default.png'),
    fullPage: true,
  });
});
